-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mpd_data_processor_main_avgB is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_avgASamples_dout : IN STD_LOGIC_VECTOR (12 downto 0);
    s_avgASamples_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    s_avgASamples_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    s_avgASamples_empty_n : IN STD_LOGIC;
    s_avgASamples_read : OUT STD_LOGIC;
    s_avgBSamplesOut_din : OUT STD_LOGIC_VECTOR (12 downto 0);
    s_avgBSamplesOut_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    s_avgBSamplesOut_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    s_avgBSamplesOut_full_n : IN STD_LOGIC;
    s_avgBSamplesOut_write : OUT STD_LOGIC;
    s_avgAHeader_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    s_avgAHeader_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    s_avgAHeader_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    s_avgAHeader_empty_n : IN STD_LOGIC;
    s_avgAHeader_read : OUT STD_LOGIC;
    s_avgBPreHeader_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    s_avgBPreHeader_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    s_avgBPreHeader_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    s_avgBPreHeader_full_n : IN STD_LOGIC;
    s_avgBPreHeader_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_apvThrB_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    m_apvThrB_ce0 : OUT STD_LOGIC;
    m_apvThrB_q0 : IN STD_LOGIC_VECTOR (12 downto 0) );
end;


architecture behav of mpd_data_processor_main_avgB is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter0_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv13_FFF : STD_LOGIC_VECTOR (12 downto 0) := "0111111111111";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_CS_iter0_fsm_state2 : STD_LOGIC;
    signal ps_2_load_reg_550 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_32_i_reg_554 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op21_read_state2 : BOOLEAN;
    signal ap_predicate_op22_write_state2 : BOOLEAN;
    signal tmp_i_41_reg_569 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op30_read_state2 : BOOLEAN;
    signal tmp_i_reg_573 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op39_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ps_2_load_reg_550_pp0_iter0_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_reg_573_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal avg_header_tag_reg_600 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln149_reg_604 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_predicate_op104_write_state3 : BOOLEAN;
    signal ap_predicate_op111_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_CS_iter1_fsm_state3 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ps_2 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    signal avg_pre_header_sum_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal avg_pre_header_cnt_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal apv_id_2 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal avg_pre_header_tag_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal n : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal avg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal s_avgAHeader_blk_n : STD_LOGIC;
    signal s_avgBPreHeader_blk_n : STD_LOGIC;
    signal s_avgASamples_blk_n : STD_LOGIC;
    signal s_avgBSamplesOut_blk_n : STD_LOGIC;
    signal ps_2_load_load_fu_195_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_32_i_nbreadreq_fu_120_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_i_reg_554_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal n_load_reg_558 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nbreadreq_fu_128_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sample_data_reg_577 : STD_LOGIC_VECTOR (12 downto 0);
    signal m_apvThrB_load_reg_583 : STD_LOGIC_VECTOR (12 downto 0);
    signal s_avgAHeader_read_reg_595 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_187_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln149_fu_274_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_storemerge_i_phi_fu_179_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_storemerge_i_reg_176 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln199_1_fu_225_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln206_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln202_fu_433_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_36_i_fu_457_p5 : STD_LOGIC_VECTOR (19 downto 0);
    signal icmp_ln200_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln203_fu_445_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln206_fu_236_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal avg_header_avg_fu_258_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln212_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln172_fu_487_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln158_fu_533_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_203_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln199_fu_215_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln199_1_fu_219_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_18_i_fu_336_p5 : STD_LOGIC_VECTOR (40 downto 0);
    signal sext_ln199_1_fu_360_p0 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln199_1_fu_360_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln199_fu_353_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln199_fu_364_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal thr_fu_378_p0 : STD_LOGIC_VECTOR (12 downto 0);
    signal thr_fu_378_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_22_fu_370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_383_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln199_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln199_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln199_1_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln199_fu_409_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal thr_1_fu_417_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln202_fu_430_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln172_cast_fu_475_p5 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_19_i_fu_492_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_20_i_fu_501_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_35_i_fu_509_p5 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln158_cast_fu_521_p5 : STD_LOGIC_VECTOR (40 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter0_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state3_blk : STD_LOGIC;
    signal ap_condition_273 : BOOLEAN;
    signal ap_condition_128 : BOOLEAN;
    signal ap_condition_267 : BOOLEAN;
    signal ap_condition_121 : BOOLEAN;
    signal ap_condition_231 : BOOLEAN;
    signal ap_condition_252 : BOOLEAN;
    signal ap_condition_144 : BOOLEAN;
    signal ap_condition_248 : BOOLEAN;
    signal ap_condition_260 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    avg_pre_header_cnt_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_267)) then
                if ((ap_const_boolean_1 = ap_condition_128)) then 
                    avg_pre_header_cnt_1 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_condition_273)) then 
                    avg_pre_header_cnt_1 <= add_ln203_fu_445_p2;
                end if;
            end if; 
        end if;
    end process;

    avg_pre_header_sum_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_267)) then
                if ((ap_const_boolean_1 = ap_condition_128)) then 
                    avg_pre_header_sum_1 <= ap_const_lv20_0;
                elsif ((ap_const_boolean_1 = ap_condition_121)) then 
                    avg_pre_header_sum_1 <= tmp_36_i_fu_457_p5;
                elsif ((ap_const_boolean_1 = ap_condition_273)) then 
                    avg_pre_header_sum_1 <= add_ln202_fu_433_p2;
                end if;
            end if; 
        end if;
    end process;

    avg_pre_header_tag_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_231)) then
                if ((trunc_ln149_fu_274_p1 = ap_const_lv2_1)) then 
                    avg_pre_header_tag_1 <= ap_const_lv1_0;
                elsif ((trunc_ln149_fu_274_p1 = ap_const_lv2_2)) then 
                    avg_pre_header_tag_1 <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    n_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_144)) then
                if ((ap_const_boolean_1 = ap_condition_252)) then 
                    n <= ap_const_lv8_0;
                elsif (((tmp_32_i_reg_554 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_3))) then 
                    n <= add_ln206_fu_236_p2;
                end if;
            end if; 
        end if;
    end process;

    ps_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_144)) then
                if ((ap_const_boolean_1 = ap_condition_260)) then 
                    ps_2 <= ap_const_lv3_5;
                elsif ((ap_const_boolean_1 = ap_condition_252)) then 
                    ps_2 <= ap_const_lv3_2;
                elsif (((tmp_i_41_reg_569 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_2))) then 
                    ps_2 <= ap_phi_mux_storemerge_i_phi_fu_179_p4;
                elsif ((ap_const_boolean_1 = ap_condition_248)) then 
                    ps_2 <= ap_const_lv3_4;
                elsif ((ps_2_load_reg_550 = ap_const_lv3_4)) then 
                    ps_2 <= ap_const_lv3_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (tmp_i_reg_573 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2) and (trunc_ln149_fu_274_p1 = ap_const_lv2_1) and (grp_fu_187_p3 = 
    ap_const_lv1_1))) then
                apv_id_2 <= s_avgAHeader_dout(5 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (tmp_i_41_reg_569 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2) and (grp_fu_187_p3 = ap_const_lv1_0))) then
                avg <= avg_header_avg_fu_258_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (tmp_i_reg_573 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then
                avg_header_tag_reg_600 <= s_avgAHeader_dout(16 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (tmp_32_i_reg_554 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_3) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then
                m_apvThrB_load_reg_583 <= m_apvThrB_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (tmp_32_i_nbreadreq_fu_120_p3 = ap_const_lv1_1) and (ps_2_load_load_fu_195_p1 = ap_const_lv3_3))) then
                n_load_reg_558 <= n;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                ps_2_load_reg_550 <= ps_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then
                ps_2_load_reg_550_pp0_iter0_reg <= ps_2_load_reg_550;
                tmp_32_i_reg_554_pp0_iter0_reg <= tmp_32_i_reg_554;
                tmp_i_reg_573_pp0_iter0_reg <= tmp_i_reg_573;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_predicate_op39_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then
                s_avgAHeader_read_reg_595 <= s_avgAHeader_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_predicate_op21_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then
                sample_data_reg_577 <= s_avgASamples_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ps_2_load_load_fu_195_p1 = ap_const_lv3_3))) then
                tmp_32_i_reg_554 <= tmp_32_i_nbreadreq_fu_120_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ps_2_load_load_fu_195_p1 = ap_const_lv3_2))) then
                tmp_i_41_reg_569 <= grp_nbreadreq_fu_128_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ps_2_load_load_fu_195_p1 = ap_const_lv3_1))) then
                tmp_i_reg_573 <= grp_nbreadreq_fu_128_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (tmp_i_reg_573 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2) and (grp_fu_187_p3 = ap_const_lv1_1))) then
                trunc_ln149_reg_604 <= trunc_ln149_fu_274_p1;
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (real_start, ap_CS_iter0_fsm, ap_CS_iter0_fsm_state1, s_avgASamples_empty_n, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2, s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state2;
                else
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
                end if;
            when ap_ST_iter0_fsm_state2 => 
                if (not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0))))))) then
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
                else
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state2;
                end if;
            when others =>  
                ap_NS_iter0_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter1_fsm, ap_CS_iter0_fsm_state2, s_avgASamples_empty_n, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2, s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state3 => 
                if ((not((((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)))) and not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state3;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state2) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state2) and (((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0))))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state3;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state3;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;
    add_ln199_1_fu_219_p2 <= std_logic_vector(unsigned(tmp_fu_203_p3) + unsigned(zext_ln199_fu_215_p1));
    add_ln199_fu_364_p2 <= std_logic_vector(signed(sext_ln199_1_fu_360_p1) + signed(sext_ln199_fu_353_p1));
    add_ln202_fu_433_p2 <= std_logic_vector(unsigned(avg_pre_header_sum_1) + unsigned(sext_ln202_fu_430_p1));
    add_ln203_fu_445_p2 <= std_logic_vector(unsigned(avg_pre_header_cnt_1) + unsigned(ap_const_lv8_1));
    add_ln206_fu_236_p2 <= std_logic_vector(unsigned(n_load_reg_558) + unsigned(ap_const_lv8_1));
    and_ln199_fu_397_p2 <= (xor_ln199_fu_391_p2 and tmp_23_fu_383_p3);
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter0_fsm_state2 <= ap_CS_iter0_fsm(1);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state3 <= ap_CS_iter1_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter0_fsm_state2_blk_assign_proc : process(s_avgASamples_empty_n, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2)
    begin
        if ((((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)))) then 
            ap_ST_iter0_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter1_fsm_state3_blk_assign_proc : process(s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3)
    begin
        if ((((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))) then 
            ap_ST_iter1_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(s_avgASamples_empty_n, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2)
    begin
                ap_block_state2_pp0_stage1_iter0 <= (((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)));
    end process;


    ap_condition_121_assign_proc : process(ps_2_load_reg_550_pp0_iter0_reg, tmp_i_reg_573_pp0_iter0_reg, avg_header_tag_reg_600, trunc_ln149_reg_604)
    begin
                ap_condition_121 <= ((trunc_ln149_reg_604 = ap_const_lv2_2) and (avg_header_tag_reg_600 = ap_const_lv1_1) and (tmp_i_reg_573_pp0_iter0_reg = ap_const_lv1_1) and (ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_1));
    end process;


    ap_condition_128_assign_proc : process(ps_2_load_reg_550_pp0_iter0_reg, tmp_i_reg_573_pp0_iter0_reg, avg_header_tag_reg_600, trunc_ln149_reg_604)
    begin
                ap_condition_128 <= ((trunc_ln149_reg_604 = ap_const_lv2_1) and (avg_header_tag_reg_600 = ap_const_lv1_1) and (tmp_i_reg_573_pp0_iter0_reg = ap_const_lv1_1) and (ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_1));
    end process;


    ap_condition_144_assign_proc : process(ap_CS_iter0_fsm_state2, s_avgASamples_empty_n, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2, s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
                ap_condition_144 <= (not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2));
    end process;


    ap_condition_231_assign_proc : process(ap_CS_iter0_fsm_state2, s_avgASamples_empty_n, ps_2_load_reg_550, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, tmp_i_reg_573, ap_predicate_op39_read_state2, s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg, grp_fu_187_p3)
    begin
                ap_condition_231 <= (not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (tmp_i_reg_573 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2) and (grp_fu_187_p3 = ap_const_lv1_1));
    end process;


    ap_condition_248_assign_proc : process(ps_2_load_reg_550, tmp_32_i_reg_554, icmp_ln206_fu_247_p2)
    begin
                ap_condition_248 <= ((tmp_32_i_reg_554 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_3) and (icmp_ln206_fu_247_p2 = ap_const_lv1_1));
    end process;


    ap_condition_252_assign_proc : process(ps_2_load_reg_550, tmp_i_reg_573, grp_fu_187_p3, trunc_ln149_fu_274_p1)
    begin
                ap_condition_252 <= ((tmp_i_reg_573 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_1) and (trunc_ln149_fu_274_p1 = ap_const_lv2_1) and (grp_fu_187_p3 = ap_const_lv1_1));
    end process;


    ap_condition_260_assign_proc : process(ps_2_load_reg_550, tmp_i_reg_573, grp_fu_187_p3, trunc_ln149_fu_274_p1)
    begin
                ap_condition_260 <= (((tmp_i_reg_573 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_1) and (grp_fu_187_p3 = ap_const_lv1_0)) or (not((trunc_ln149_fu_274_p1 = ap_const_lv2_2)) and not((trunc_ln149_fu_274_p1 = ap_const_lv2_1)) and (tmp_i_reg_573 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_1)));
    end process;


    ap_condition_267_assign_proc : process(s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
                ap_condition_267 <= (not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state3));
    end process;


    ap_condition_273_assign_proc : process(ps_2_load_reg_550_pp0_iter0_reg, tmp_32_i_reg_554_pp0_iter0_reg, icmp_ln200_fu_425_p2)
    begin
                ap_condition_273 <= ((icmp_ln200_fu_425_p2 = ap_const_lv1_0) and (tmp_32_i_reg_554_pp0_iter0_reg = ap_const_lv1_1) and (ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_3));
    end process;


    ap_done_assign_proc : process(s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0)
    begin
        if (((ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_storemerge_i_phi_fu_179_p4_assign_proc : process(ps_2_load_reg_550, tmp_i_41_reg_569, grp_fu_187_p3, ap_phi_reg_pp0_iter0_storemerge_i_reg_176)
    begin
        if (((tmp_i_41_reg_569 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_2))) then
            if ((grp_fu_187_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_storemerge_i_phi_fu_179_p4 <= ap_const_lv3_5;
            elsif ((grp_fu_187_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_storemerge_i_phi_fu_179_p4 <= ap_const_lv3_3;
            else 
                ap_phi_mux_storemerge_i_phi_fu_179_p4 <= ap_phi_reg_pp0_iter0_storemerge_i_reg_176;
            end if;
        else 
            ap_phi_mux_storemerge_i_phi_fu_179_p4 <= ap_phi_reg_pp0_iter0_storemerge_i_reg_176;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_storemerge_i_reg_176 <= "XXX";

    ap_predicate_op104_write_state3_assign_proc : process(ps_2_load_reg_550_pp0_iter0_reg, tmp_i_reg_573_pp0_iter0_reg, avg_header_tag_reg_600, trunc_ln149_reg_604)
    begin
                ap_predicate_op104_write_state3 <= ((trunc_ln149_reg_604 = ap_const_lv2_2) and (avg_header_tag_reg_600 = ap_const_lv1_1) and (tmp_i_reg_573_pp0_iter0_reg = ap_const_lv1_1) and (ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_1));
    end process;


    ap_predicate_op111_write_state3_assign_proc : process(ps_2_load_reg_550_pp0_iter0_reg, tmp_i_reg_573_pp0_iter0_reg, avg_header_tag_reg_600, trunc_ln149_reg_604)
    begin
                ap_predicate_op111_write_state3 <= ((trunc_ln149_reg_604 = ap_const_lv2_1) and (avg_header_tag_reg_600 = ap_const_lv1_1) and (tmp_i_reg_573_pp0_iter0_reg = ap_const_lv1_1) and (ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_1));
    end process;


    ap_predicate_op21_read_state2_assign_proc : process(ps_2_load_reg_550, tmp_32_i_reg_554)
    begin
                ap_predicate_op21_read_state2 <= ((tmp_32_i_reg_554 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_3));
    end process;


    ap_predicate_op22_write_state2_assign_proc : process(ps_2_load_reg_550, tmp_32_i_reg_554)
    begin
                ap_predicate_op22_write_state2 <= ((tmp_32_i_reg_554 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_3));
    end process;


    ap_predicate_op30_read_state2_assign_proc : process(ps_2_load_reg_550, tmp_i_41_reg_569)
    begin
                ap_predicate_op30_read_state2 <= ((tmp_i_41_reg_569 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_2));
    end process;


    ap_predicate_op39_read_state2_assign_proc : process(ps_2_load_reg_550, tmp_i_reg_573)
    begin
                ap_predicate_op39_read_state2 <= ((tmp_i_reg_573 = ap_const_lv1_1) and (ps_2_load_reg_550 = ap_const_lv3_1));
    end process;

    ap_ready <= internal_ap_ready;
    avg_header_avg_fu_258_p1 <= s_avgAHeader_dout(13 - 1 downto 0);
    grp_fu_187_p3 <= s_avgAHeader_dout(16 downto 16);
    grp_nbreadreq_fu_128_p3 <= (0=>(s_avgAHeader_empty_n), others=>'-');
    icmp_ln200_fu_425_p2 <= "1" when (signed(sample_data_reg_577) > signed(thr_1_fu_417_p3)) else "0";
    icmp_ln206_fu_247_p2 <= "1" when (n_load_reg_558 = ap_const_lv8_7F) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_iter0_fsm_state2, s_avgASamples_empty_n, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2, s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    m_apvThrB_address0 <= zext_ln199_1_fu_225_p1(11 - 1 downto 0);

    m_apvThrB_ce0_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            m_apvThrB_ce0 <= ap_const_logic_1;
        else 
            m_apvThrB_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ps_2_load_load_fu_195_p1 <= ps_2;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    s_avgAHeader_blk_n_assign_proc : process(ap_CS_iter0_fsm_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2)
    begin
        if ((((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2)))) then 
            s_avgAHeader_blk_n <= s_avgAHeader_empty_n;
        else 
            s_avgAHeader_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_avgAHeader_read_assign_proc : process(ap_CS_iter0_fsm_state2, s_avgASamples_empty_n, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2, s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_predicate_op39_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2)) or (not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) 
    and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_predicate_op30_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2)))) then 
            s_avgAHeader_read <= ap_const_logic_1;
        else 
            s_avgAHeader_read <= ap_const_logic_0;
        end if; 
    end process;


    s_avgASamples_blk_n_assign_proc : process(ap_CS_iter0_fsm_state2, s_avgASamples_empty_n, ap_predicate_op21_read_state2)
    begin
        if (((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then 
            s_avgASamples_blk_n <= s_avgASamples_empty_n;
        else 
            s_avgASamples_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_avgASamples_read_assign_proc : process(ap_CS_iter0_fsm_state2, s_avgASamples_empty_n, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2, s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_predicate_op21_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then 
            s_avgASamples_read <= ap_const_logic_1;
        else 
            s_avgASamples_read <= ap_const_logic_0;
        end if; 
    end process;


    s_avgBPreHeader_blk_n_assign_proc : process(s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3)
    begin
        if ((((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (ap_predicate_op111_write_state3 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (ap_predicate_op104_write_state3 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4)))) then 
            s_avgBPreHeader_blk_n <= s_avgBPreHeader_full_n;
        else 
            s_avgBPreHeader_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_avgBPreHeader_din_assign_proc : process(ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, zext_ln212_fu_348_p1, zext_ln172_fu_487_p1, zext_ln158_fu_533_p1, ap_condition_267)
    begin
        if ((ap_const_boolean_1 = ap_condition_267)) then
            if ((ap_predicate_op111_write_state3 = ap_const_boolean_1)) then 
                s_avgBPreHeader_din <= zext_ln158_fu_533_p1;
            elsif ((ap_predicate_op104_write_state3 = ap_const_boolean_1)) then 
                s_avgBPreHeader_din <= zext_ln172_fu_487_p1;
            elsif ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4)) then 
                s_avgBPreHeader_din <= zext_ln212_fu_348_p1;
            else 
                s_avgBPreHeader_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            s_avgBPreHeader_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    s_avgBPreHeader_write_assign_proc : process(s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (ap_predicate_op111_write_state3 = ap_const_boolean_1)) or (not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (ap_predicate_op104_write_state3 = ap_const_boolean_1)) or (not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op111_write_state3 = ap_const_boolean_1) 
    and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4)))) then 
            s_avgBPreHeader_write <= ap_const_logic_1;
        else 
            s_avgBPreHeader_write <= ap_const_logic_0;
        end if; 
    end process;


    s_avgBSamplesOut_blk_n_assign_proc : process(ap_CS_iter0_fsm_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2)
    begin
        if (((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then 
            s_avgBSamplesOut_blk_n <= s_avgBSamplesOut_full_n;
        else 
            s_avgBSamplesOut_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_avgBSamplesOut_din <= s_avgASamples_dout;

    s_avgBSamplesOut_write_assign_proc : process(ap_CS_iter0_fsm_state2, s_avgASamples_empty_n, ap_predicate_op21_read_state2, s_avgBSamplesOut_full_n, ap_predicate_op22_write_state2, s_avgAHeader_empty_n, ap_predicate_op30_read_state2, ap_predicate_op39_read_state2, s_avgBPreHeader_full_n, ps_2_load_reg_550_pp0_iter0_reg, ap_predicate_op104_write_state3, ap_predicate_op111_write_state3, ap_CS_iter1_fsm_state3, ap_done_reg)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (s_avgAHeader_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_write_state2 = ap_const_boolean_1) and (s_avgBSamplesOut_full_n = ap_const_logic_0)) or ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (s_avgASamples_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state3) and (((ap_predicate_op111_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ap_predicate_op104_write_state3 = ap_const_boolean_1) and (s_avgBPreHeader_full_n = ap_const_logic_0)) or ((ps_2_load_reg_550_pp0_iter0_reg = ap_const_lv3_4) and (s_avgBPreHeader_full_n = ap_const_logic_0)))))) and (ap_predicate_op22_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then 
            s_avgBSamplesOut_write <= ap_const_logic_1;
        else 
            s_avgBSamplesOut_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln199_fu_409_p3 <= 
        ap_const_lv13_FFF when (and_ln199_fu_397_p2(0) = '1') else 
        ap_const_lv13_1000;
    sext_ln199_1_fu_360_p0 <= avg;
        sext_ln199_1_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln199_1_fu_360_p0),14));

        sext_ln199_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m_apvThrB_load_reg_583),14));

        sext_ln202_fu_430_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sample_data_reg_577),20));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    thr_1_fu_417_p3 <= 
        select_ln199_fu_409_p3 when (xor_ln199_1_fu_403_p2(0) = '1') else 
        thr_fu_378_p2;
    thr_fu_378_p0 <= avg;
    thr_fu_378_p2 <= std_logic_vector(signed(thr_fu_378_p0) + signed(m_apvThrB_load_reg_583));
    tmp_18_i_fu_336_p5 <= (((avg_pre_header_tag_1 & avg_pre_header_cnt_1) & ap_const_lv12_0) & avg_pre_header_sum_1);
    tmp_19_i_fu_492_p4 <= s_avgAHeader_read_reg_595(10 downto 2);
    tmp_20_i_fu_501_p3 <= (tmp_19_i_fu_492_p4 & ap_const_lv2_1);
    tmp_22_fu_370_p3 <= add_ln199_fu_364_p2(13 downto 13);
    tmp_23_fu_383_p3 <= thr_fu_378_p2(12 downto 12);
    tmp_32_i_nbreadreq_fu_120_p3 <= (0=>(s_avgASamples_empty_n), others=>'-');
    tmp_35_i_fu_509_p5 <= (avg_pre_header_sum_1(19 downto 11) & tmp_20_i_fu_501_p3);
    tmp_36_i_fu_457_p5 <= (avg_pre_header_sum_1(19 downto 2) & ap_const_lv2_2);
    tmp_fu_203_p3 <= (apv_id_2 & ap_const_lv7_0);
    trunc_ln149_fu_274_p1 <= s_avgAHeader_dout(2 - 1 downto 0);
    xor_ln199_1_fu_403_p2 <= (tmp_23_fu_383_p3 xor tmp_22_fu_370_p3);
    xor_ln199_fu_391_p2 <= (tmp_22_fu_370_p3 xor ap_const_lv1_1);
    zext_ln158_cast_fu_521_p5 <= (((ap_const_lv1_1 & avg_pre_header_cnt_1) & ap_const_lv12_0) & tmp_35_i_fu_509_p5);
    zext_ln158_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln158_cast_fu_521_p5),64));
    zext_ln172_cast_fu_475_p5 <= (((ap_const_lv1_1 & avg_pre_header_cnt_1) & ap_const_lv12_0) & tmp_36_i_fu_457_p5);
    zext_ln172_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln172_cast_fu_475_p5),64));
    zext_ln199_1_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln199_1_fu_219_p2),64));
    zext_ln199_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n),11));
    zext_ln212_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_i_fu_336_p5),64));
end behav;
