// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mpd_data_processor_main_avgB (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_avgASamples_dout,
        s_avgASamples_num_data_valid,
        s_avgASamples_fifo_cap,
        s_avgASamples_empty_n,
        s_avgASamples_read,
        s_avgBSamplesOut_din,
        s_avgBSamplesOut_num_data_valid,
        s_avgBSamplesOut_fifo_cap,
        s_avgBSamplesOut_full_n,
        s_avgBSamplesOut_write,
        s_avgAHeader_dout,
        s_avgAHeader_num_data_valid,
        s_avgAHeader_fifo_cap,
        s_avgAHeader_empty_n,
        s_avgAHeader_read,
        s_avgBPreHeader_din,
        s_avgBPreHeader_num_data_valid,
        s_avgBPreHeader_fifo_cap,
        s_avgBPreHeader_full_n,
        s_avgBPreHeader_write,
        start_out,
        start_write,
        m_apvThrB_address0,
        m_apvThrB_ce0,
        m_apvThrB_q0
);

parameter    ap_ST_iter0_fsm_state1 = 2'd1;
parameter    ap_ST_iter0_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [12:0] s_avgASamples_dout;
input  [2:0] s_avgASamples_num_data_valid;
input  [2:0] s_avgASamples_fifo_cap;
input   s_avgASamples_empty_n;
output   s_avgASamples_read;
output  [12:0] s_avgBSamplesOut_din;
input  [1:0] s_avgBSamplesOut_num_data_valid;
input  [1:0] s_avgBSamplesOut_fifo_cap;
input   s_avgBSamplesOut_full_n;
output   s_avgBSamplesOut_write;
input  [31:0] s_avgAHeader_dout;
input  [1:0] s_avgAHeader_num_data_valid;
input  [1:0] s_avgAHeader_fifo_cap;
input   s_avgAHeader_empty_n;
output   s_avgAHeader_read;
output  [63:0] s_avgBPreHeader_din;
input  [1:0] s_avgBPreHeader_num_data_valid;
input  [1:0] s_avgBPreHeader_fifo_cap;
input   s_avgBPreHeader_full_n;
output   s_avgBPreHeader_write;
output   start_out;
output   start_write;
output  [10:0] m_apvThrB_address0;
output   m_apvThrB_ce0;
input  [12:0] m_apvThrB_q0;

reg ap_done;
reg ap_idle;
reg s_avgASamples_read;
reg s_avgBSamplesOut_write;
reg s_avgAHeader_read;
reg[63:0] s_avgBPreHeader_din;
reg s_avgBPreHeader_write;
reg start_write;
reg m_apvThrB_ce0;

reg    real_start;
reg    start_once_reg;
reg   [1:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg    internal_ap_ready;
wire    ap_CS_iter0_fsm_state2;
reg   [2:0] ps_2_load_reg_550;
reg   [0:0] tmp_32_i_reg_554;
reg    ap_predicate_op21_read_state2;
reg    ap_predicate_op22_write_state2;
reg   [0:0] tmp_i_41_reg_569;
reg    ap_predicate_op30_read_state2;
reg   [0:0] tmp_i_reg_573;
reg    ap_predicate_op39_read_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg   [2:0] ps_2_load_reg_550_pp0_iter0_reg;
reg   [0:0] tmp_i_reg_573_pp0_iter0_reg;
reg   [0:0] avg_header_tag_reg_600;
reg   [1:0] trunc_ln149_reg_604;
reg    ap_predicate_op104_write_state3;
reg    ap_predicate_op111_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state3;
reg    ap_done_reg;
reg   [2:0] ps_2;
reg   [19:0] avg_pre_header_sum_1;
reg   [7:0] avg_pre_header_cnt_1;
reg   [3:0] apv_id_2;
reg   [0:0] avg_pre_header_tag_1;
reg   [7:0] n;
reg   [12:0] avg;
reg    s_avgAHeader_blk_n;
reg    s_avgBPreHeader_blk_n;
reg    s_avgASamples_blk_n;
reg    s_avgBSamplesOut_blk_n;
wire   [2:0] ps_2_load_load_fu_195_p1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] tmp_32_i_nbreadreq_fu_120_p3;
reg   [0:0] tmp_32_i_reg_554_pp0_iter0_reg;
reg   [7:0] n_load_reg_558;
wire   [0:0] grp_nbreadreq_fu_128_p3;
reg  signed [12:0] sample_data_reg_577;
reg  signed [12:0] m_apvThrB_load_reg_583;
reg   [31:0] s_avgAHeader_read_reg_595;
wire   [0:0] grp_fu_187_p3;
wire   [1:0] trunc_ln149_fu_274_p1;
reg   [2:0] ap_phi_mux_storemerge_i_phi_fu_179_p4;
wire   [2:0] ap_phi_reg_pp0_iter0_storemerge_i_reg_176;
wire   [63:0] zext_ln199_1_fu_225_p1;
wire   [0:0] icmp_ln206_fu_247_p2;
wire   [19:0] add_ln202_fu_433_p2;
wire   [19:0] tmp_36_i_fu_457_p5;
wire   [0:0] icmp_ln200_fu_425_p2;
wire   [7:0] add_ln203_fu_445_p2;
wire   [7:0] add_ln206_fu_236_p2;
wire   [12:0] avg_header_avg_fu_258_p1;
wire   [63:0] zext_ln212_fu_348_p1;
wire   [63:0] zext_ln172_fu_487_p1;
wire   [63:0] zext_ln158_fu_533_p1;
wire   [10:0] tmp_fu_203_p3;
wire   [10:0] zext_ln199_fu_215_p1;
wire   [10:0] add_ln199_1_fu_219_p2;
wire   [40:0] tmp_18_i_fu_336_p5;
wire  signed [12:0] sext_ln199_1_fu_360_p0;
wire  signed [13:0] sext_ln199_1_fu_360_p1;
wire  signed [13:0] sext_ln199_fu_353_p1;
wire   [13:0] add_ln199_fu_364_p2;
wire  signed [12:0] thr_fu_378_p0;
wire   [12:0] thr_fu_378_p2;
wire   [0:0] tmp_22_fu_370_p3;
wire   [0:0] tmp_23_fu_383_p3;
wire   [0:0] xor_ln199_fu_391_p2;
wire   [0:0] and_ln199_fu_397_p2;
wire   [0:0] xor_ln199_1_fu_403_p2;
wire   [12:0] select_ln199_fu_409_p3;
wire   [12:0] thr_1_fu_417_p3;
wire  signed [19:0] sext_ln202_fu_430_p1;
wire   [40:0] zext_ln172_cast_fu_475_p5;
wire   [8:0] tmp_19_i_fu_492_p4;
wire   [10:0] tmp_20_i_fu_501_p3;
wire   [19:0] tmp_35_i_fu_509_p5;
wire   [40:0] zext_ln158_cast_fu_521_p5;
reg   [1:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter0_fsm_state2_blk;
reg    ap_ST_iter1_fsm_state3_blk;
reg    ap_condition_273;
reg    ap_condition_128;
reg    ap_condition_267;
reg    ap_condition_121;
reg    ap_condition_231;
reg    ap_condition_252;
reg    ap_condition_144;
reg    ap_condition_248;
reg    ap_condition_260;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_iter0_fsm = 2'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 ps_2 = 3'd1;
#0 avg_pre_header_sum_1 = 20'd0;
#0 avg_pre_header_cnt_1 = 8'd0;
#0 apv_id_2 = 4'd0;
#0 avg_pre_header_tag_1 = 1'd0;
#0 n = 8'd0;
#0 avg = 13'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_267)) begin
        if ((1'b1 == ap_condition_128)) begin
            avg_pre_header_cnt_1 <= 8'd0;
        end else if ((1'b1 == ap_condition_273)) begin
            avg_pre_header_cnt_1 <= add_ln203_fu_445_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_267)) begin
        if ((1'b1 == ap_condition_128)) begin
            avg_pre_header_sum_1 <= 20'd0;
        end else if ((1'b1 == ap_condition_121)) begin
            avg_pre_header_sum_1 <= tmp_36_i_fu_457_p5;
        end else if ((1'b1 == ap_condition_273)) begin
            avg_pre_header_sum_1 <= add_ln202_fu_433_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_231)) begin
        if ((trunc_ln149_fu_274_p1 == 2'd1)) begin
            avg_pre_header_tag_1 <= 1'd0;
        end else if ((trunc_ln149_fu_274_p1 == 2'd2)) begin
            avg_pre_header_tag_1 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((1'b1 == ap_condition_252)) begin
            n <= 8'd0;
        end else if (((tmp_32_i_reg_554 == 1'd1) & (ps_2_load_reg_550 == 3'd3))) begin
            n <= add_ln206_fu_236_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((1'b1 == ap_condition_260)) begin
            ps_2 <= 3'd5;
        end else if ((1'b1 == ap_condition_252)) begin
            ps_2 <= 3'd2;
        end else if (((tmp_i_41_reg_569 == 1'd1) & (ps_2_load_reg_550 == 3'd2))) begin
            ps_2 <= ap_phi_mux_storemerge_i_phi_fu_179_p4;
        end else if ((1'b1 == ap_condition_248)) begin
            ps_2 <= 3'd4;
        end else if ((ps_2_load_reg_550 == 3'd4)) begin
            ps_2 <= 3'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (tmp_i_reg_573 == 1'd1) & (ps_2_load_reg_550 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (trunc_ln149_fu_274_p1 == 2'd1) & (grp_fu_187_p3 == 1'd1))) begin
        apv_id_2 <= {{s_avgAHeader_dout[5:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (tmp_i_41_reg_569 == 1'd1) & (ps_2_load_reg_550 == 3'd2) & (1'b1 == ap_CS_iter0_fsm_state2) & (grp_fu_187_p3 == 1'd0))) begin
        avg <= avg_header_avg_fu_258_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (tmp_i_reg_573 == 1'd1) & (ps_2_load_reg_550 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        avg_header_tag_reg_600 <= s_avgAHeader_dout[32'd16];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (tmp_32_i_reg_554 == 1'd1) & (ps_2_load_reg_550 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        m_apvThrB_load_reg_583 <= m_apvThrB_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (tmp_32_i_nbreadreq_fu_120_p3 == 1'd1) & (ps_2_load_load_fu_195_p1 == 3'd3))) begin
        n_load_reg_558 <= n;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ps_2_load_reg_550 <= ps_2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ps_2_load_reg_550_pp0_iter0_reg <= ps_2_load_reg_550;
        tmp_32_i_reg_554_pp0_iter0_reg <= tmp_32_i_reg_554;
        tmp_i_reg_573_pp0_iter0_reg <= tmp_i_reg_573;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (ap_predicate_op39_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        s_avgAHeader_read_reg_595 <= s_avgAHeader_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (ap_predicate_op21_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        sample_data_reg_577 <= s_avgASamples_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ps_2_load_load_fu_195_p1 == 3'd3))) begin
        tmp_32_i_reg_554 <= tmp_32_i_nbreadreq_fu_120_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ps_2_load_load_fu_195_p1 == 3'd2))) begin
        tmp_i_41_reg_569 <= grp_nbreadreq_fu_128_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ps_2_load_load_fu_195_p1 == 3'd1))) begin
        tmp_i_reg_573 <= grp_nbreadreq_fu_128_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (tmp_i_reg_573 == 1'd1) & (ps_2_load_reg_550 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (grp_fu_187_p3 == 1'd1))) begin
        trunc_ln149_reg_604 <= trunc_ln149_fu_274_p1;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)))) begin
        ap_ST_iter0_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0)))) begin
        ap_ST_iter1_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_41_reg_569 == 1'd1) & (ps_2_load_reg_550 == 3'd2))) begin
        if ((grp_fu_187_p3 == 1'd1)) begin
            ap_phi_mux_storemerge_i_phi_fu_179_p4 = 3'd5;
        end else if ((grp_fu_187_p3 == 1'd0)) begin
            ap_phi_mux_storemerge_i_phi_fu_179_p4 = 3'd3;
        end else begin
            ap_phi_mux_storemerge_i_phi_fu_179_p4 = ap_phi_reg_pp0_iter0_storemerge_i_reg_176;
        end
    end else begin
        ap_phi_mux_storemerge_i_phi_fu_179_p4 = ap_phi_reg_pp0_iter0_storemerge_i_reg_176;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        m_apvThrB_ce0 = 1'b1;
    end else begin
        m_apvThrB_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((((ap_predicate_op39_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | ((ap_predicate_op30_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        s_avgAHeader_blk_n = s_avgAHeader_empty_n;
    end else begin
        s_avgAHeader_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (ap_predicate_op39_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n 
    == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (ap_predicate_op30_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        s_avgAHeader_read = 1'b1;
    end else begin
        s_avgAHeader_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op21_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        s_avgASamples_blk_n = s_avgASamples_empty_n;
    end else begin
        s_avgASamples_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (ap_predicate_op21_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        s_avgASamples_read = 1'b1;
    end else begin
        s_avgASamples_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op111_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op104_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (ps_2_load_reg_550_pp0_iter0_reg == 3'd4)))) begin
        s_avgBPreHeader_blk_n = s_avgBPreHeader_full_n;
    end else begin
        s_avgBPreHeader_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_267)) begin
        if ((ap_predicate_op111_write_state3 == 1'b1)) begin
            s_avgBPreHeader_din = zext_ln158_fu_533_p1;
        end else if ((ap_predicate_op104_write_state3 == 1'b1)) begin
            s_avgBPreHeader_din = zext_ln172_fu_487_p1;
        end else if ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4)) begin
            s_avgBPreHeader_din = zext_ln212_fu_348_p1;
        end else begin
            s_avgBPreHeader_din = 'bx;
        end
    end else begin
        s_avgBPreHeader_din = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op111_write_state3 == 1'b1)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op104_write_state3 == 1'b1)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state3) & (ps_2_load_reg_550_pp0_iter0_reg 
    == 3'd4)))) begin
        s_avgBPreHeader_write = 1'b1;
    end else begin
        s_avgBPreHeader_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op22_write_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        s_avgBSamplesOut_blk_n = s_avgBSamplesOut_full_n;
    end else begin
        s_avgBSamplesOut_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (ap_predicate_op22_write_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        s_avgBSamplesOut_write = 1'b1;
    end else begin
        s_avgBSamplesOut_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end
        end
        ap_ST_iter0_fsm_state2 : begin
            if (~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0)))))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state3 : begin
            if ((~(((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0))) & ~((ap_done_reg == 1'b1) | ((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state2) | ((1'b1 == ap_CS_iter0_fsm_state2) & (((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln199_1_fu_219_p2 = (tmp_fu_203_p3 + zext_ln199_fu_215_p1);

assign add_ln199_fu_364_p2 = ($signed(sext_ln199_1_fu_360_p1) + $signed(sext_ln199_fu_353_p1));

assign add_ln202_fu_433_p2 = ($signed(avg_pre_header_sum_1) + $signed(sext_ln202_fu_430_p1));

assign add_ln203_fu_445_p2 = (avg_pre_header_cnt_1 + 8'd1);

assign add_ln206_fu_236_p2 = (n_load_reg_558 + 8'd1);

assign and_ln199_fu_397_p2 = (xor_ln199_fu_391_p2 & tmp_23_fu_383_p3);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter0_fsm_state2 = ap_CS_iter0_fsm[32'd1];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state3 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_121 = ((trunc_ln149_reg_604 == 2'd2) & (avg_header_tag_reg_600 == 1'd1) & (tmp_i_reg_573_pp0_iter0_reg == 1'd1) & (ps_2_load_reg_550_pp0_iter0_reg == 3'd1));
end

always @ (*) begin
    ap_condition_128 = ((trunc_ln149_reg_604 == 2'd1) & (avg_header_tag_reg_600 == 1'd1) & (tmp_i_reg_573_pp0_iter0_reg == 1'd1) & (ps_2_load_reg_550_pp0_iter0_reg == 3'd1));
end

always @ (*) begin
    ap_condition_144 = (~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2));
end

always @ (*) begin
    ap_condition_231 = (~((ap_done_reg == 1'b1) | ((ap_predicate_op39_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op30_read_state2 == 1'b1) & (s_avgAHeader_empty_n == 1'b0)) | ((ap_predicate_op22_write_state2 == 1'b1) & (s_avgBSamplesOut_full_n == 1'b0)) | ((ap_predicate_op21_read_state2 == 1'b1) & (s_avgASamples_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))))) & (tmp_i_reg_573 == 1'd1) & (ps_2_load_reg_550 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (grp_fu_187_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_248 = ((tmp_32_i_reg_554 == 1'd1) & (ps_2_load_reg_550 == 3'd3) & (icmp_ln206_fu_247_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_252 = ((tmp_i_reg_573 == 1'd1) & (ps_2_load_reg_550 == 3'd1) & (trunc_ln149_fu_274_p1 == 2'd1) & (grp_fu_187_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_260 = (((tmp_i_reg_573 == 1'd1) & (ps_2_load_reg_550 == 3'd1) & (grp_fu_187_p3 == 1'd0)) | (~(trunc_ln149_fu_274_p1 == 2'd2) & ~(trunc_ln149_fu_274_p1 == 2'd1) & (tmp_i_reg_573 == 1'd1) & (ps_2_load_reg_550 == 3'd1)));
end

always @ (*) begin
    ap_condition_267 = (~((ap_done_reg == 1'b1) | ((ap_predicate_op111_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ap_predicate_op104_write_state3 == 1'b1) & (s_avgBPreHeader_full_n == 1'b0)) | ((ps_2_load_reg_550_pp0_iter0_reg == 3'd4) & (s_avgBPreHeader_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state3));
end

always @ (*) begin
    ap_condition_273 = ((icmp_ln200_fu_425_p2 == 1'd0) & (tmp_32_i_reg_554_pp0_iter0_reg == 1'd1) & (ps_2_load_reg_550_pp0_iter0_reg == 3'd3));
end

assign ap_phi_reg_pp0_iter0_storemerge_i_reg_176 = 'bx;

always @ (*) begin
    ap_predicate_op104_write_state3 = ((trunc_ln149_reg_604 == 2'd2) & (avg_header_tag_reg_600 == 1'd1) & (tmp_i_reg_573_pp0_iter0_reg == 1'd1) & (ps_2_load_reg_550_pp0_iter0_reg == 3'd1));
end

always @ (*) begin
    ap_predicate_op111_write_state3 = ((trunc_ln149_reg_604 == 2'd1) & (avg_header_tag_reg_600 == 1'd1) & (tmp_i_reg_573_pp0_iter0_reg == 1'd1) & (ps_2_load_reg_550_pp0_iter0_reg == 3'd1));
end

always @ (*) begin
    ap_predicate_op21_read_state2 = ((tmp_32_i_reg_554 == 1'd1) & (ps_2_load_reg_550 == 3'd3));
end

always @ (*) begin
    ap_predicate_op22_write_state2 = ((tmp_32_i_reg_554 == 1'd1) & (ps_2_load_reg_550 == 3'd3));
end

always @ (*) begin
    ap_predicate_op30_read_state2 = ((tmp_i_41_reg_569 == 1'd1) & (ps_2_load_reg_550 == 3'd2));
end

always @ (*) begin
    ap_predicate_op39_read_state2 = ((tmp_i_reg_573 == 1'd1) & (ps_2_load_reg_550 == 3'd1));
end

assign ap_ready = internal_ap_ready;

assign avg_header_avg_fu_258_p1 = s_avgAHeader_dout[12:0];

assign grp_fu_187_p3 = s_avgAHeader_dout[32'd16];

assign grp_nbreadreq_fu_128_p3 = s_avgAHeader_empty_n;

assign icmp_ln200_fu_425_p2 = (($signed(sample_data_reg_577) > $signed(thr_1_fu_417_p3)) ? 1'b1 : 1'b0);

assign icmp_ln206_fu_247_p2 = ((n_load_reg_558 == 8'd127) ? 1'b1 : 1'b0);

assign m_apvThrB_address0 = zext_ln199_1_fu_225_p1;

assign ps_2_load_load_fu_195_p1 = ps_2;

assign s_avgBSamplesOut_din = s_avgASamples_dout;

assign select_ln199_fu_409_p3 = ((and_ln199_fu_397_p2[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign sext_ln199_1_fu_360_p0 = avg;

assign sext_ln199_1_fu_360_p1 = sext_ln199_1_fu_360_p0;

assign sext_ln199_fu_353_p1 = m_apvThrB_load_reg_583;

assign sext_ln202_fu_430_p1 = sample_data_reg_577;

assign start_out = real_start;

assign thr_1_fu_417_p3 = ((xor_ln199_1_fu_403_p2[0:0] == 1'b1) ? select_ln199_fu_409_p3 : thr_fu_378_p2);

assign thr_fu_378_p0 = avg;

assign thr_fu_378_p2 = ($signed(thr_fu_378_p0) + $signed(m_apvThrB_load_reg_583));

assign tmp_18_i_fu_336_p5 = {{{{avg_pre_header_tag_1}, {avg_pre_header_cnt_1}}, {12'd0}}, {avg_pre_header_sum_1}};

assign tmp_19_i_fu_492_p4 = {{s_avgAHeader_read_reg_595[10:2]}};

assign tmp_20_i_fu_501_p3 = {{tmp_19_i_fu_492_p4}, {2'd1}};

assign tmp_22_fu_370_p3 = add_ln199_fu_364_p2[32'd13];

assign tmp_23_fu_383_p3 = thr_fu_378_p2[32'd12];

assign tmp_32_i_nbreadreq_fu_120_p3 = s_avgASamples_empty_n;

assign tmp_35_i_fu_509_p5 = {{avg_pre_header_sum_1[19:11]}, {tmp_20_i_fu_501_p3}};

assign tmp_36_i_fu_457_p5 = {{avg_pre_header_sum_1[19:2]}, {2'd2}};

assign tmp_fu_203_p3 = {{apv_id_2}, {7'd0}};

assign trunc_ln149_fu_274_p1 = s_avgAHeader_dout[1:0];

assign xor_ln199_1_fu_403_p2 = (tmp_23_fu_383_p3 ^ tmp_22_fu_370_p3);

assign xor_ln199_fu_391_p2 = (tmp_22_fu_370_p3 ^ 1'd1);

assign zext_ln158_cast_fu_521_p5 = {{{{{{1'd1}, {avg_pre_header_cnt_1}}}, {12'd0}}}, {tmp_35_i_fu_509_p5}};

assign zext_ln158_fu_533_p1 = zext_ln158_cast_fu_521_p5;

assign zext_ln172_cast_fu_475_p5 = {{{{{{1'd1}, {avg_pre_header_cnt_1}}}, {12'd0}}}, {tmp_36_i_fu_457_p5}};

assign zext_ln172_fu_487_p1 = zext_ln172_cast_fu_475_p5;

assign zext_ln199_1_fu_225_p1 = add_ln199_1_fu_219_p2;

assign zext_ln199_fu_215_p1 = n;

assign zext_ln212_fu_348_p1 = tmp_18_i_fu_336_p5;

endmodule //mpd_data_processor_main_avgB
