// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mpd_data_processor_main_event_writer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_evOut_din,
        s_evOut_full_n,
        s_evOut_write,
        s_avgBSamplesIn_dout,
        s_avgBSamplesIn_num_data_valid,
        s_avgBSamplesIn_fifo_cap,
        s_avgBSamplesIn_empty_n,
        s_avgBSamplesIn_read,
        s_avgBHeader_dout,
        s_avgBHeader_num_data_valid,
        s_avgBHeader_fifo_cap,
        s_avgBHeader_empty_n,
        s_avgBHeader_read,
        build_all_samples,
        enable_cm,
        fiber,
        m_apvThr_address0,
        m_apvThr_ce0,
        m_apvThr_q0
);

parameter    ap_ST_iter0_fsm_state1 = 2'd1;
parameter    ap_ST_iter0_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [32:0] s_evOut_din;
input   s_evOut_full_n;
output   s_evOut_write;
input  [31:0] s_avgBSamplesIn_dout;
input  [1:0] s_avgBSamplesIn_num_data_valid;
input  [1:0] s_avgBSamplesIn_fifo_cap;
input   s_avgBSamplesIn_empty_n;
output   s_avgBSamplesIn_read;
input  [31:0] s_avgBHeader_dout;
input  [2:0] s_avgBHeader_num_data_valid;
input  [2:0] s_avgBHeader_fifo_cap;
input   s_avgBHeader_empty_n;
output   s_avgBHeader_read;
input  [0:0] build_all_samples;
input  [0:0] enable_cm;
input  [4:0] fiber;
output  [10:0] m_apvThr_address0;
output   m_apvThr_ce0;
input  [12:0] m_apvThr_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[32:0] s_evOut_din;
reg s_evOut_write;
reg s_avgBSamplesIn_read;
reg s_avgBHeader_read;
reg m_apvThr_ce0;

reg   [1:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire    ap_CS_iter0_fsm_state2;
reg   [2:0] ps_1_load_reg_1311;
reg   [0:0] tmp_16_i_reg_1349;
reg    ap_predicate_op131_read_state2;
reg   [0:0] tmp_i_34_reg_1353;
reg    ap_predicate_op162_read_state2;
reg   [0:0] tmp_i_reg_1357;
reg    ap_predicate_op198_read_state2;
reg   [2:0] ps_1_load_reg_1311_pp0_iter0_reg;
reg   [0:0] tmp_i_reg_1357_pp0_iter0_reg;
reg   [0:0] avg_header_tag_reg_1394;
wire   [0:0] avg_header_tag_reg_1394_pp0_iter0_reg;
reg   [1:0] trunc_ln293_reg_1406;
reg    ap_predicate_op245_write_state3;
reg   [0:0] icmp_ln297_reg_1415;
reg    ap_predicate_op249_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state3;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_done_reg;
reg   [2:0] ps_1;
reg   [3:0] apv_id_1;
reg   [6:0] sample_n;
reg   [12:0] event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5;
reg   [12:0] event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_4;
reg   [15:0] sum;
reg   [12:0] event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_3;
reg   [12:0] event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_2;
reg   [2:0] cnt;
reg   [2:0] avgB_1_address0;
reg    avgB_1_ce0;
reg    avgB_1_we0;
wire   [12:0] avgB_1_d0;
wire   [12:0] avgB_1_q0;
reg   [2:0] avgB_1_address1;
reg    avgB_1_ce1;
wire   [12:0] avgB_1_q1;
reg   [12:0] event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_1;
reg   [12:0] event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s;
reg    s_evOut_blk_n;
reg    s_avgBHeader_blk_n;
reg    s_avgBSamplesIn_blk_n;
wire   [2:0] ps_1_load_load_fu_293_p1;
wire   [0:0] grp_nbreadreq_fu_164_p3;
reg   [0:0] build_all_samples_read_reg_1307;
reg    ap_predicate_op11_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [3:0] apv_id_1_load_reg_1315;
reg   [3:0] apv_id_1_load_reg_1315_pp0_iter0_reg;
reg   [6:0] sample_n_load_reg_1320;
reg   [0:0] tmp_17_i_reg_1328;
wire  signed [12:0] sample_data_pair_4_fu_305_p1;
reg  signed [12:0] sample_data_pair_4_reg_1332;
wire  signed [12:0] grp_fu_273_p4;
reg  signed [12:0] sample_data_pair_5_reg_1338;
reg   [0:0] tmp_16_i_reg_1349_pp0_iter0_reg;
reg   [0:0] tmp_i_34_reg_1353_pp0_iter0_reg;
wire   [0:0] tmp_i_nbreadreq_fu_178_p3;
reg   [4:0] fiber_read_reg_1361;
reg   [15:0] sum_load_reg_1366;
wire  signed [12:0] select_ln353_4_fu_915_p3;
reg  signed [12:0] select_ln353_4_reg_1374;
wire  signed [12:0] select_ln353_5_fu_923_p3;
reg  signed [12:0] select_ln353_5_reg_1379;
wire  signed [12:0] select_ln353_2_fu_1083_p3;
reg  signed [12:0] select_ln353_2_reg_1384;
wire  signed [12:0] select_ln353_3_fu_1091_p3;
reg  signed [12:0] select_ln353_3_reg_1389;
wire   [0:0] avg_header_tag_fu_1132_p3;
wire   [2:0] add_ln316_fu_1144_p2;
wire   [1:0] trunc_ln293_fu_1173_p1;
reg   [4:0] mpd_id_1_reg_1410;
wire   [0:0] icmp_ln297_fu_1203_p2;
reg   [2:0] ap_phi_mux_storemerge5_i_phi_fu_252_p6;
wire   [2:0] zext_ln377_fu_764_p1;
wire   [0:0] or_ln371_1_fu_752_p2;
wire   [2:0] ap_phi_reg_pp0_iter0_cnt_new_0_i_reg_262;
reg   [2:0] ap_phi_reg_pp0_iter1_cnt_new_0_i_reg_262;
wire   [0:0] icmp_ln317_fu_1155_p2;
wire   [63:0] zext_ln366_fu_317_p1;
wire   [63:0] zext_ln316_fu_1150_p1;
wire   [2:0] zext_ln417_fu_1117_p1;
wire   [6:0] grp_fu_283_p2;
wire   [15:0] add_ln344_1_fu_1225_p2;
wire  signed [15:0] sext_ln333_2_fu_1248_p1;
wire  signed [15:0] add_ln355_1_fu_594_p2;
wire  signed [12:0] select_ln353_6_fu_550_p3;
wire  signed [12:0] select_ln353_7_fu_557_p3;
wire   [32:0] zext_ln402_fu_379_p1;
wire   [32:0] zext_ln390_fu_405_p1;
wire   [32:0] zext_ln414_fu_1281_p1;
wire   [32:0] zext_ln305_fu_1302_p1;
wire   [10:0] tmp_fu_309_p3;
wire   [1:0] tmp_21_i_fu_354_p4;
wire   [4:0] zext_ln399_fu_363_p1;
wire   [31:0] tmp_22_i_fu_367_p5;
wire   [4:0] trunc_ln387_fu_390_p1;
wire   [31:0] tmp_20_i_fu_393_p5;
wire  signed [13:0] sext_ln353_fu_416_p1;
wire  signed [13:0] sext_ln353_1_fu_419_p1;
wire   [13:0] sub_ln353_fu_423_p2;
wire   [0:0] tmp_16_fu_429_p3;
wire   [0:0] tmp_17_fu_441_p3;
wire   [0:0] xor_ln353_fu_449_p2;
wire   [0:0] and_ln353_fu_455_p2;
wire   [0:0] xor_ln353_1_fu_461_p2;
wire   [12:0] select_ln353_fu_467_p3;
wire   [12:0] trunc_ln353_fu_437_p1;
wire  signed [13:0] sext_ln354_fu_483_p1;
wire  signed [13:0] sext_ln354_1_fu_486_p1;
wire   [13:0] sub_ln354_fu_490_p2;
wire   [0:0] tmp_18_fu_496_p3;
wire   [0:0] tmp_19_fu_508_p3;
wire   [0:0] xor_ln354_fu_516_p2;
wire   [0:0] and_ln354_fu_522_p2;
wire   [0:0] xor_ln354_1_fu_528_p2;
wire   [12:0] select_ln354_fu_534_p3;
wire   [12:0] trunc_ln354_fu_504_p1;
wire   [12:0] select_ln353_1_fu_475_p3;
wire   [12:0] select_ln354_1_fu_542_p3;
wire  signed [13:0] sext_ln355_1_fu_580_p1;
wire  signed [13:0] sext_ln355_fu_576_p1;
wire   [13:0] add_ln355_fu_584_p2;
wire  signed [15:0] sext_ln355_2_fu_590_p1;
wire   [0:0] icmp_ln362_4_fu_654_p2;
wire   [0:0] icmp_ln362_3_fu_642_p2;
wire   [0:0] icmp_ln362_2_fu_630_p2;
wire   [0:0] icmp_ln362_1_fu_618_p2;
wire   [0:0] icmp_ln362_fu_606_p2;
wire   [0:0] icmp_ln363_4_fu_674_p2;
wire   [0:0] icmp_ln363_3_fu_648_p2;
wire   [0:0] icmp_ln363_2_fu_636_p2;
wire   [0:0] icmp_ln363_1_fu_624_p2;
wire   [0:0] icmp_ln363_fu_612_p2;
wire   [13:0] shl_ln366_1_fu_702_p3;
wire   [15:0] shl_ln_fu_694_p3;
wire  signed [15:0] sext_ln366_fu_710_p1;
wire   [15:0] sum_thr_fu_714_p2;
wire  signed [16:0] sext_ln371_fu_720_p1;
wire   [16:0] zext_ln371_fu_724_p1;
wire   [4:0] max_pos0_test_fu_660_p6;
wire   [4:0] max_pos5_test_fu_680_p6;
wire   [0:0] icmp_ln371_1_fu_734_p2;
wire   [0:0] icmp_ln371_2_fu_740_p2;
wire   [0:0] or_ln371_fu_746_p2;
wire   [0:0] icmp_ln371_fu_728_p2;
wire   [0:0] grp_fu_288_p2;
wire  signed [12:0] sample_data_pair_2_fu_775_p1;
wire  signed [13:0] sext_ln342_fu_779_p1;
wire  signed [13:0] sext_ln342_1_fu_783_p1;
wire   [13:0] sub_ln342_fu_787_p2;
wire   [0:0] tmp_12_fu_793_p3;
wire   [0:0] tmp_13_fu_805_p3;
wire   [0:0] xor_ln342_fu_813_p2;
wire   [0:0] and_ln342_fu_819_p2;
wire   [0:0] xor_ln342_1_fu_825_p2;
wire   [12:0] select_ln342_fu_831_p3;
wire   [12:0] trunc_ln342_fu_801_p1;
wire  signed [13:0] sext_ln343_fu_847_p1;
wire  signed [13:0] sext_ln343_1_fu_851_p1;
wire   [13:0] sub_ln343_fu_855_p2;
wire   [0:0] tmp_14_fu_861_p3;
wire   [0:0] tmp_15_fu_873_p3;
wire   [0:0] xor_ln343_fu_881_p2;
wire   [0:0] and_ln343_fu_887_p2;
wire   [0:0] xor_ln343_1_fu_893_p2;
wire   [12:0] select_ln343_fu_899_p3;
wire   [12:0] trunc_ln343_fu_869_p1;
wire   [12:0] select_ln342_1_fu_839_p3;
wire   [12:0] select_ln343_1_fu_907_p3;
wire  signed [12:0] sample_data_pair_fu_943_p1;
wire  signed [13:0] sext_ln331_fu_947_p1;
wire  signed [13:0] sext_ln331_1_fu_951_p1;
wire   [13:0] sub_ln331_fu_955_p2;
wire   [0:0] tmp_8_fu_961_p3;
wire   [0:0] tmp_9_fu_973_p3;
wire   [0:0] xor_ln331_fu_981_p2;
wire   [0:0] and_ln331_fu_987_p2;
wire   [0:0] xor_ln331_1_fu_993_p2;
wire   [12:0] select_ln331_fu_999_p3;
wire   [12:0] trunc_ln331_fu_969_p1;
wire  signed [13:0] sext_ln332_fu_1015_p1;
wire  signed [13:0] sext_ln332_1_fu_1019_p1;
wire   [13:0] sub_ln332_fu_1023_p2;
wire   [0:0] tmp_10_fu_1029_p3;
wire   [0:0] tmp_11_fu_1041_p3;
wire   [0:0] xor_ln332_fu_1049_p2;
wire   [0:0] and_ln332_fu_1055_p2;
wire   [0:0] xor_ln332_1_fu_1061_p2;
wire   [12:0] select_ln332_fu_1067_p3;
wire   [12:0] trunc_ln332_fu_1037_p1;
wire   [12:0] select_ln331_1_fu_1007_p3;
wire   [12:0] select_ln332_1_fu_1075_p3;
wire  signed [13:0] sext_ln344_1_fu_1212_p1;
wire  signed [13:0] sext_ln344_fu_1209_p1;
wire   [13:0] add_ln344_fu_1215_p2;
wire  signed [15:0] sext_ln344_2_fu_1221_p1;
wire  signed [13:0] sext_ln333_1_fu_1239_p1;
wire  signed [13:0] sext_ln333_fu_1236_p1;
wire   [13:0] add_ln333_fu_1242_p2;
wire   [4:0] zext_ln411_fu_1266_p1;
wire   [31:0] tmp_18_i_fu_1269_p5;
wire   [31:0] zext_ln305_cast_fu_1292_p5;
reg   [1:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter0_fsm_state2_blk;
reg    ap_ST_iter1_fsm_state3_blk;
reg    ap_condition_321;
reg    ap_condition_339;
reg    ap_condition_347;
reg    ap_condition_148;
reg    ap_condition_1020;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 2'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 ps_1 = 3'd0;
#0 apv_id_1 = 4'd0;
#0 sample_n = 7'd0;
#0 event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5 = 13'd0;
#0 event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_4 = 13'd0;
#0 sum = 16'd0;
#0 event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_3 = 13'd0;
#0 event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_2 = 13'd0;
#0 cnt = 3'd0;
#0 event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_1 = 13'd0;
#0 event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s = 13'd0;
end

mpd_data_processor_main_event_writer_avgB_1_RAM_AUTO_1R1W #(
    .DataWidth( 13 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
avgB_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(avgB_1_address0),
    .ce0(avgB_1_ce0),
    .we0(avgB_1_we0),
    .d0(avgB_1_d0),
    .q0(avgB_1_q0),
    .address1(avgB_1_address1),
    .ce1(avgB_1_ce1),
    .q1(avgB_1_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_148)) begin
        if ((1'b1 == ap_condition_347)) begin
            ap_phi_reg_pp0_iter1_cnt_new_0_i_reg_262 <= add_ln316_fu_1144_p2;
        end else if ((1'b1 == ap_condition_339)) begin
            ap_phi_reg_pp0_iter1_cnt_new_0_i_reg_262 <= 3'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_cnt_new_0_i_reg_262 <= ap_phi_reg_pp0_iter0_cnt_new_0_i_reg_262;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1_load_load_fu_293_p1 == 3'd1))) begin
        ps_1 <= 3'd2;
    end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1_load_load_fu_293_p1 == 3'd2))) begin
        ps_1 <= 3'd3;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2) & (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0) & (icmp_ln317_fu_1155_p2 == 1'd1) & (avg_header_tag_fu_1132_p3 == 1'd0)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7) & (icmp_ln317_fu_1155_p2 == 1'd1) & (avg_header_tag_fu_1132_p3 == 1'd0))))) begin
        ps_1 <= 3'd1;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd6) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ps_1 <= zext_ln417_fu_1117_p1;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state2) & (tmp_17_i_reg_1328 == 1'd1))) begin
        ps_1 <= ap_phi_mux_storemerge5_i_phi_fu_252_p6;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ps_1 <= 3'd5;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd5) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ps_1 <= 3'd6;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2) & (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0) & (icmp_ln317_fu_1155_p2 == 1'd1) & (avg_header_tag_fu_1132_p3 == 1'd0)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7) & (icmp_ln317_fu_1155_p2 == 1'd1) & (avg_header_tag_fu_1132_p3 == 1'd0))))) begin
        sample_n <= 7'd0;
    end else if (((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd6) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n 
    == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd3) & (or_ln371_1_fu_752_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (tmp_17_i_reg_1328 == 1'd1) & (build_all_samples_read_reg_1307 == 1'd0)))) begin
        sample_n <= grp_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state2) & (tmp_17_i_reg_1328 == 1'd1))) begin
        sum <= add_ln355_1_fu_594_p2;
    end else if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (ps_1_load_reg_1311_pp0_iter0_reg == 3'd1) & (1'b1 == ap_CS_iter1_fsm_state3) & (tmp_i_34_reg_1353_pp0_iter0_reg == 1'd1))) begin
        sum <= sext_ln333_2_fu_1248_p1;
    end else if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (ps_1_load_reg_1311_pp0_iter0_reg == 3'd2) & (1'b1 == ap_CS_iter1_fsm_state3) & (tmp_16_i_reg_1349_pp0_iter0_reg == 1'd1))) begin
        sum <= add_ln344_1_fu_1225_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2) & (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0) & (trunc_ln293_fu_1173_p1 == 2'd1) & (avg_header_tag_fu_1132_p3 == 1'd1)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7) & (trunc_ln293_fu_1173_p1 == 2'd1) & (avg_header_tag_fu_1132_p3 == 1'd1))))) begin
        apv_id_1 <= {{s_avgBHeader_dout[5:2]}};
        icmp_ln297_reg_1415 <= icmp_ln297_fu_1203_p2;
        mpd_id_1_reg_1410 <= {{s_avgBHeader_dout[10:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        apv_id_1_load_reg_1315 <= apv_id_1;
        build_all_samples_read_reg_1307 <= build_all_samples;
        ps_1_load_reg_1311 <= ps_1;
        sample_n_load_reg_1320 <= sample_n;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        apv_id_1_load_reg_1315_pp0_iter0_reg <= apv_id_1_load_reg_1315;
        fiber_read_reg_1361 <= fiber;
        ps_1_load_reg_1311_pp0_iter0_reg <= ps_1_load_reg_1311;
        sum_load_reg_1366 <= sum;
        tmp_16_i_reg_1349_pp0_iter0_reg <= tmp_16_i_reg_1349;
        tmp_i_34_reg_1353_pp0_iter0_reg <= tmp_i_34_reg_1353;
        tmp_i_reg_1357_pp0_iter0_reg <= tmp_i_reg_1357;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2) & (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7))))) begin
        avg_header_tag_reg_1394 <= s_avgBHeader_dout[32'd16];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd0) & (avg_header_tag_reg_1394_pp0_iter0_reg == 1'd0) & (tmp_i_reg_1357_pp0_iter0_reg == 1'd1)) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd7) & (avg_header_tag_reg_1394_pp0_iter0_reg == 1'd0) & (tmp_i_reg_1357_pp0_iter0_reg == 1'd1))))) begin
        cnt <= ap_phi_reg_pp0_iter1_cnt_new_0_i_reg_262;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state2) & (tmp_17_i_reg_1328 == 1'd1))) begin
        event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s <= select_ln353_7_fu_557_p3;
        event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_1 <= select_ln353_6_fu_550_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (tmp_16_i_reg_1349 == 1'd1) & (ps_1_load_reg_1311 == 3'd2) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_2 <= select_ln353_5_fu_923_p3;
        event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_3 <= select_ln353_4_fu_915_p3;
        select_ln353_4_reg_1374 <= select_ln353_4_fu_915_p3;
        select_ln353_5_reg_1379 <= select_ln353_5_fu_923_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (tmp_i_34_reg_1353 == 1'd1) & (ps_1_load_reg_1311 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_4 <= select_ln353_3_fu_1091_p3;
        event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5 <= select_ln353_2_fu_1083_p3;
        select_ln353_2_reg_1384 <= select_ln353_2_fu_1083_p3;
        select_ln353_3_reg_1389 <= select_ln353_3_fu_1091_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1 == 3'd3))) begin
        sample_data_pair_4_reg_1332 <= sample_data_pair_4_fu_305_p1;
        sample_data_pair_5_reg_1338 <= {{s_avgBSamplesIn_dout[28:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ps_1_load_load_fu_293_p1 == 3'd2))) begin
        tmp_16_i_reg_1349 <= grp_nbreadreq_fu_164_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ps_1 == 3'd3))) begin
        tmp_17_i_reg_1328 <= grp_nbreadreq_fu_164_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ps_1_load_load_fu_293_p1 == 3'd1))) begin
        tmp_i_34_reg_1353 <= grp_nbreadreq_fu_164_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & ((ps_1_load_load_fu_293_p1 == 3'd0) | (ps_1_load_load_fu_293_p1 == 3'd7)))) begin
        tmp_i_reg_1357 <= tmp_i_nbreadreq_fu_178_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2) & (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0) & (avg_header_tag_fu_1132_p3 == 1'd1)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7) & (avg_header_tag_fu_1132_p3 == 1'd1))))) begin
        trunc_ln293_reg_1406 <= trunc_ln293_fu_1173_p1;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1)))))) begin
        ap_ST_iter0_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1)))) begin
        ap_ST_iter1_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_321)) begin
        if ((or_ln371_1_fu_752_p2 == 1'd0)) begin
            ap_phi_mux_storemerge5_i_phi_fu_252_p6 = 3'd4;
        end else if ((or_ln371_1_fu_752_p2 == 1'd1)) begin
            ap_phi_mux_storemerge5_i_phi_fu_252_p6 = zext_ln377_fu_764_p1;
        end else begin
            ap_phi_mux_storemerge5_i_phi_fu_252_p6 = 3'd4;
        end
    end else begin
        ap_phi_mux_storemerge5_i_phi_fu_252_p6 = 3'd4;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state2) & (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0) & (avg_header_tag_fu_1132_p3 == 1'd0)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7) & (avg_header_tag_fu_1132_p3 == 1'd0))))) begin
        avgB_1_address0 = zext_ln316_fu_1150_p1;
    end else if (((1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1_load_load_fu_293_p1 == 3'd1) & (ap_start == 1'b1))) begin
        avgB_1_address0 = 3'd1;
    end else if (((1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1_load_load_fu_293_p1 == 3'd2) & (ap_start == 1'b1))) begin
        avgB_1_address0 = 3'd3;
    end else if (((1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1 == 3'd3) & (ap_start == 1'b1))) begin
        avgB_1_address0 = 3'd5;
    end else begin
        avgB_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1020)) begin
        if ((ps_1_load_load_fu_293_p1 == 3'd1)) begin
            avgB_1_address1 = 3'd0;
        end else if ((ps_1_load_load_fu_293_p1 == 3'd2)) begin
            avgB_1_address1 = 3'd2;
        end else if ((ps_1 == 3'd3)) begin
            avgB_1_address1 = 3'd4;
        end else begin
            avgB_1_address1 = 'bx;
        end
    end else begin
        avgB_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1_load_load_fu_293_p1 == 3'd1)) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1_load_load_fu_293_p1 == 3'd2)) | (~((ap_done_reg == 1'b1) | (ap_start 
    == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1 == 3'd3)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n 
    == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2) & (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0) & (avg_header_tag_fu_1132_p3 == 1'd0)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7) & (avg_header_tag_fu_1132_p3 == 1'd0)))))) begin
        avgB_1_ce0 = 1'b1;
    end else begin
        avgB_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1_load_load_fu_293_p1 == 3'd1)) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1_load_load_fu_293_p1 == 3'd2)) | (~((ap_done_reg == 1'b1) | (ap_start 
    == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1 == 3'd3)))) begin
        avgB_1_ce1 = 1'b1;
    end else begin
        avgB_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2) & (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0) & (avg_header_tag_fu_1132_p3 == 1'd0)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7) & (avg_header_tag_fu_1132_p3 == 1'd0))))) begin
        avgB_1_we0 = 1'b1;
    end else begin
        avgB_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        m_apvThr_ce0 = 1'b1;
    end else begin
        m_apvThr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op198_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        s_avgBHeader_blk_n = s_avgBHeader_empty_n;
    end else begin
        s_avgBHeader_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ap_predicate_op198_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        s_avgBHeader_read = 1'b1;
    end else begin
        s_avgBHeader_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op162_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | ((ap_predicate_op131_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1 == 3'd3) & (ap_start == 1'b1)))) begin
        s_avgBSamplesIn_blk_n = s_avgBSamplesIn_empty_n;
    end else begin
        s_avgBSamplesIn_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op11_read_state1 == 1'b1)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 
    == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ap_predicate_op162_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ap_predicate_op131_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        s_avgBSamplesIn_read = 1'b1;
    end else begin
        s_avgBSamplesIn_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (1'b1 == ap_CS_iter1_fsm_state3)) | ((ps_1_load_reg_1311 == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state2)) | ((ps_1_load_reg_1311 == 3'd5) & (1'b1 == ap_CS_iter0_fsm_state2)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op249_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op245_write_state3 == 1'b1)))) begin
        s_evOut_blk_n = s_evOut_full_n;
    end else begin
        s_evOut_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op249_write_state3 == 1'b1))) begin
        s_evOut_din = zext_ln305_fu_1302_p1;
    end else if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op245_write_state3 == 1'b1))) begin
        s_evOut_din = 33'd8589934591;
    end else if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        s_evOut_din = zext_ln414_fu_1281_p1;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        s_evOut_din = zext_ln390_fu_405_p1;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd5) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        s_evOut_din = zext_ln402_fu_379_p1;
    end else begin
        s_evOut_din = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (1'b1 == ap_CS_iter1_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op249_write_state3 == 1'b1)) | (~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op245_write_state3 == 1'b1)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 
    == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n 
    == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (ps_1_load_reg_1311 == 3'd5) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        s_evOut_write = 1'b1;
    end else begin
        s_evOut_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end
        end
        ap_ST_iter0_fsm_state2 : begin
            if (~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1)))))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & ~(((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))) & ((1'b0 == ap_CS_iter0_fsm_state2) | ((1'b1 == ap_CS_iter0_fsm_state2) & (((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln316_fu_1144_p2 = (cnt + 3'd1);

assign add_ln333_fu_1242_p2 = ($signed(sext_ln333_1_fu_1239_p1) + $signed(sext_ln333_fu_1236_p1));

assign add_ln344_1_fu_1225_p2 = ($signed(sum_load_reg_1366) + $signed(sext_ln344_2_fu_1221_p1));

assign add_ln344_fu_1215_p2 = ($signed(sext_ln344_1_fu_1212_p1) + $signed(sext_ln344_fu_1209_p1));

assign add_ln355_1_fu_594_p2 = ($signed(sum) + $signed(sext_ln355_2_fu_590_p1));

assign add_ln355_fu_584_p2 = ($signed(sext_ln355_1_fu_580_p1) + $signed(sext_ln355_fu_576_p1));

assign and_ln331_fu_987_p2 = (xor_ln331_fu_981_p2 & tmp_9_fu_973_p3);

assign and_ln332_fu_1055_p2 = (xor_ln332_fu_1049_p2 & tmp_11_fu_1041_p3);

assign and_ln342_fu_819_p2 = (xor_ln342_fu_813_p2 & tmp_13_fu_805_p3);

assign and_ln343_fu_887_p2 = (xor_ln343_fu_881_p2 & tmp_15_fu_873_p3);

assign and_ln353_fu_455_p2 = (xor_ln353_fu_449_p2 & tmp_17_fu_441_p3);

assign and_ln354_fu_522_p2 = (xor_ln354_fu_516_p2 & tmp_19_fu_508_p3);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter0_fsm_state2 = ap_CS_iter0_fsm[32'd1];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state3 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((s_avgBSamplesIn_empty_n == 1'b0) & (ap_predicate_op11_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_condition_1020 = ((1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_164_p3 == 1'd1) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_condition_148 = (~((ap_done_reg == 1'b1) | ((ap_predicate_op198_read_state2 == 1'b1) & (s_avgBHeader_empty_n == 1'b0)) | ((ap_predicate_op162_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ap_predicate_op131_read_state2 == 1'b1) & (s_avgBSamplesIn_empty_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd4) & (s_evOut_full_n == 1'b0)) | ((ps_1_load_reg_1311 == 3'd5) & (s_evOut_full_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd6) & (s_evOut_full_n == 1'b0)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op249_write_state3 == 1'b1)) | ((s_evOut_full_n == 1'b0) & (ap_predicate_op245_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2));
end

always @ (*) begin
    ap_condition_321 = ((ps_1_load_reg_1311 == 3'd3) & (tmp_17_i_reg_1328 == 1'd1) & (build_all_samples_read_reg_1307 == 1'd0));
end

always @ (*) begin
    ap_condition_339 = (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0) & (icmp_ln317_fu_1155_p2 == 1'd1) & (avg_header_tag_fu_1132_p3 == 1'd0)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7) & (icmp_ln317_fu_1155_p2 == 1'd1) & (avg_header_tag_fu_1132_p3 == 1'd0)));
end

always @ (*) begin
    ap_condition_347 = (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0) & (icmp_ln317_fu_1155_p2 == 1'd0) & (avg_header_tag_fu_1132_p3 == 1'd0)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7) & (icmp_ln317_fu_1155_p2 == 1'd0) & (avg_header_tag_fu_1132_p3 == 1'd0)));
end

assign ap_phi_reg_pp0_iter0_cnt_new_0_i_reg_262 = 'bx;

always @ (*) begin
    ap_predicate_op11_read_state1 = ((grp_nbreadreq_fu_164_p3 == 1'd1) & (ps_1 == 3'd3));
end

always @ (*) begin
    ap_predicate_op131_read_state2 = ((tmp_16_i_reg_1349 == 1'd1) & (ps_1_load_reg_1311 == 3'd2));
end

always @ (*) begin
    ap_predicate_op162_read_state2 = ((tmp_i_34_reg_1353 == 1'd1) & (ps_1_load_reg_1311 == 3'd1));
end

always @ (*) begin
    ap_predicate_op198_read_state2 = (((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd0)) | ((tmp_i_reg_1357 == 1'd1) & (ps_1_load_reg_1311 == 3'd7)));
end

always @ (*) begin
    ap_predicate_op245_write_state3 = (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd0) & (trunc_ln293_reg_1406 == 2'd2) & (avg_header_tag_reg_1394 == 1'd1) & (tmp_i_reg_1357_pp0_iter0_reg == 1'd1)) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd7) & (trunc_ln293_reg_1406 == 2'd2) & (avg_header_tag_reg_1394 == 1'd1) & (tmp_i_reg_1357_pp0_iter0_reg == 1'd1)));
end

always @ (*) begin
    ap_predicate_op249_write_state3 = (((ps_1_load_reg_1311_pp0_iter0_reg == 3'd0) & (icmp_ln297_reg_1415 == 1'd1) & (trunc_ln293_reg_1406 == 2'd1) & (avg_header_tag_reg_1394 == 1'd1) & (tmp_i_reg_1357_pp0_iter0_reg == 1'd1)) | ((ps_1_load_reg_1311_pp0_iter0_reg == 3'd7) & (icmp_ln297_reg_1415 == 1'd1) & (trunc_ln293_reg_1406 == 2'd1) & (avg_header_tag_reg_1394 == 1'd1) & (tmp_i_reg_1357_pp0_iter0_reg == 1'd1)));
end

assign avgB_1_d0 = s_avgBHeader_dout[12:0];

assign avg_header_tag_fu_1132_p3 = s_avgBHeader_dout[32'd16];

assign avg_header_tag_reg_1394_pp0_iter0_reg = avg_header_tag_reg_1394;

assign grp_fu_273_p4 = {{s_avgBSamplesIn_dout[28:16]}};

assign grp_fu_283_p2 = (sample_n_load_reg_1320 + 7'd1);

assign grp_fu_288_p2 = ((sample_n_load_reg_1320 != 7'd127) ? 1'b1 : 1'b0);

assign grp_nbreadreq_fu_164_p3 = s_avgBSamplesIn_empty_n;

assign icmp_ln297_fu_1203_p2 = ((cnt == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln317_fu_1155_p2 = ((add_ln316_fu_1144_p2 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln362_1_fu_618_p2 = (($signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5) > $signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_3)) ? 1'b1 : 1'b0);

assign icmp_ln362_2_fu_630_p2 = (($signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5) > $signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_2)) ? 1'b1 : 1'b0);

assign icmp_ln362_3_fu_642_p2 = (($signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5) > $signed(select_ln353_6_fu_550_p3)) ? 1'b1 : 1'b0);

assign icmp_ln362_4_fu_654_p2 = (($signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5) > $signed(select_ln353_7_fu_557_p3)) ? 1'b1 : 1'b0);

assign icmp_ln362_fu_606_p2 = (($signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5) > $signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_4)) ? 1'b1 : 1'b0);

assign icmp_ln363_1_fu_624_p2 = (($signed(select_ln353_7_fu_557_p3) > $signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_4)) ? 1'b1 : 1'b0);

assign icmp_ln363_2_fu_636_p2 = (($signed(select_ln353_7_fu_557_p3) > $signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_3)) ? 1'b1 : 1'b0);

assign icmp_ln363_3_fu_648_p2 = (($signed(select_ln353_7_fu_557_p3) > $signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_2)) ? 1'b1 : 1'b0);

assign icmp_ln363_4_fu_674_p2 = (($signed(select_ln353_7_fu_557_p3) > $signed(select_ln353_6_fu_550_p3)) ? 1'b1 : 1'b0);

assign icmp_ln363_fu_612_p2 = (($signed(select_ln353_7_fu_557_p3) > $signed(event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5)) ? 1'b1 : 1'b0);

assign icmp_ln371_1_fu_734_p2 = ((max_pos0_test_fu_660_p6 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln371_2_fu_740_p2 = ((max_pos5_test_fu_680_p6 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln371_fu_728_p2 = (($signed(sext_ln371_fu_720_p1) < $signed(zext_ln371_fu_724_p1)) ? 1'b1 : 1'b0);

assign m_apvThr_address0 = zext_ln366_fu_317_p1;

assign max_pos0_test_fu_660_p6 = {{{{{icmp_ln362_4_fu_654_p2}, {icmp_ln362_3_fu_642_p2}}, {icmp_ln362_2_fu_630_p2}}, {icmp_ln362_1_fu_618_p2}}, {icmp_ln362_fu_606_p2}};

assign max_pos5_test_fu_680_p6 = {{{{{icmp_ln363_4_fu_674_p2}, {icmp_ln363_3_fu_648_p2}}, {icmp_ln363_2_fu_636_p2}}, {icmp_ln363_1_fu_624_p2}}, {icmp_ln363_fu_612_p2}};

assign or_ln371_1_fu_752_p2 = (or_ln371_fu_746_p2 | icmp_ln371_fu_728_p2);

assign or_ln371_fu_746_p2 = (icmp_ln371_2_fu_740_p2 | icmp_ln371_1_fu_734_p2);

assign ps_1_load_load_fu_293_p1 = ps_1;

assign sample_data_pair_2_fu_775_p1 = s_avgBSamplesIn_dout[12:0];

assign sample_data_pair_4_fu_305_p1 = s_avgBSamplesIn_dout[12:0];

assign sample_data_pair_fu_943_p1 = s_avgBSamplesIn_dout[12:0];

assign select_ln331_1_fu_1007_p3 = ((xor_ln331_1_fu_993_p2[0:0] == 1'b1) ? select_ln331_fu_999_p3 : trunc_ln331_fu_969_p1);

assign select_ln331_fu_999_p3 = ((and_ln331_fu_987_p2[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln332_1_fu_1075_p3 = ((xor_ln332_1_fu_1061_p2[0:0] == 1'b1) ? select_ln332_fu_1067_p3 : trunc_ln332_fu_1037_p1);

assign select_ln332_fu_1067_p3 = ((and_ln332_fu_1055_p2[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln342_1_fu_839_p3 = ((xor_ln342_1_fu_825_p2[0:0] == 1'b1) ? select_ln342_fu_831_p3 : trunc_ln342_fu_801_p1);

assign select_ln342_fu_831_p3 = ((and_ln342_fu_819_p2[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln343_1_fu_907_p3 = ((xor_ln343_1_fu_893_p2[0:0] == 1'b1) ? select_ln343_fu_899_p3 : trunc_ln343_fu_869_p1);

assign select_ln343_fu_899_p3 = ((and_ln343_fu_887_p2[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln353_1_fu_475_p3 = ((xor_ln353_1_fu_461_p2[0:0] == 1'b1) ? select_ln353_fu_467_p3 : trunc_ln353_fu_437_p1);

assign select_ln353_2_fu_1083_p3 = ((enable_cm[0:0] == 1'b1) ? select_ln331_1_fu_1007_p3 : sample_data_pair_fu_943_p1);

assign select_ln353_3_fu_1091_p3 = ((enable_cm[0:0] == 1'b1) ? select_ln332_1_fu_1075_p3 : grp_fu_273_p4);

assign select_ln353_4_fu_915_p3 = ((enable_cm[0:0] == 1'b1) ? select_ln342_1_fu_839_p3 : sample_data_pair_2_fu_775_p1);

assign select_ln353_5_fu_923_p3 = ((enable_cm[0:0] == 1'b1) ? select_ln343_1_fu_907_p3 : grp_fu_273_p4);

assign select_ln353_6_fu_550_p3 = ((enable_cm[0:0] == 1'b1) ? select_ln353_1_fu_475_p3 : sample_data_pair_4_reg_1332);

assign select_ln353_7_fu_557_p3 = ((enable_cm[0:0] == 1'b1) ? select_ln354_1_fu_542_p3 : sample_data_pair_5_reg_1338);

assign select_ln353_fu_467_p3 = ((and_ln353_fu_455_p2[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln354_1_fu_542_p3 = ((xor_ln354_1_fu_528_p2[0:0] == 1'b1) ? select_ln354_fu_534_p3 : trunc_ln354_fu_504_p1);

assign select_ln354_fu_534_p3 = ((and_ln354_fu_522_p2[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign sext_ln331_1_fu_951_p1 = $signed(avgB_1_q1);

assign sext_ln331_fu_947_p1 = sample_data_pair_fu_943_p1;

assign sext_ln332_1_fu_1019_p1 = $signed(avgB_1_q0);

assign sext_ln332_fu_1015_p1 = grp_fu_273_p4;

assign sext_ln333_1_fu_1239_p1 = select_ln353_3_reg_1389;

assign sext_ln333_2_fu_1248_p1 = $signed(add_ln333_fu_1242_p2);

assign sext_ln333_fu_1236_p1 = select_ln353_2_reg_1384;

assign sext_ln342_1_fu_783_p1 = $signed(avgB_1_q1);

assign sext_ln342_fu_779_p1 = sample_data_pair_2_fu_775_p1;

assign sext_ln343_1_fu_851_p1 = $signed(avgB_1_q0);

assign sext_ln343_fu_847_p1 = grp_fu_273_p4;

assign sext_ln344_1_fu_1212_p1 = select_ln353_5_reg_1379;

assign sext_ln344_2_fu_1221_p1 = $signed(add_ln344_fu_1215_p2);

assign sext_ln344_fu_1209_p1 = select_ln353_4_reg_1374;

assign sext_ln353_1_fu_419_p1 = $signed(avgB_1_q1);

assign sext_ln353_fu_416_p1 = sample_data_pair_4_reg_1332;

assign sext_ln354_1_fu_486_p1 = $signed(avgB_1_q0);

assign sext_ln354_fu_483_p1 = sample_data_pair_5_reg_1338;

assign sext_ln355_1_fu_580_p1 = select_ln353_7_fu_557_p3;

assign sext_ln355_2_fu_590_p1 = $signed(add_ln355_fu_584_p2);

assign sext_ln355_fu_576_p1 = select_ln353_6_fu_550_p3;

assign sext_ln366_fu_710_p1 = $signed(shl_ln366_1_fu_702_p3);

assign sext_ln371_fu_720_p1 = add_ln355_1_fu_594_p2;

assign shl_ln366_1_fu_702_p3 = {{m_apvThr_q0}, {1'd0}};

assign shl_ln_fu_694_p3 = {{m_apvThr_q0}, {3'd0}};

assign sub_ln331_fu_955_p2 = ($signed(sext_ln331_fu_947_p1) - $signed(sext_ln331_1_fu_951_p1));

assign sub_ln332_fu_1023_p2 = ($signed(sext_ln332_fu_1015_p1) - $signed(sext_ln332_1_fu_1019_p1));

assign sub_ln342_fu_787_p2 = ($signed(sext_ln342_fu_779_p1) - $signed(sext_ln342_1_fu_783_p1));

assign sub_ln343_fu_855_p2 = ($signed(sext_ln343_fu_847_p1) - $signed(sext_ln343_1_fu_851_p1));

assign sub_ln353_fu_423_p2 = ($signed(sext_ln353_fu_416_p1) - $signed(sext_ln353_1_fu_419_p1));

assign sub_ln354_fu_490_p2 = ($signed(sext_ln354_fu_483_p1) - $signed(sext_ln354_1_fu_486_p1));

assign sum_thr_fu_714_p2 = ($signed(shl_ln_fu_694_p3) - $signed(sext_ln366_fu_710_p1));

assign tmp_10_fu_1029_p3 = sub_ln332_fu_1023_p2[32'd13];

assign tmp_11_fu_1041_p3 = sub_ln332_fu_1023_p2[32'd12];

assign tmp_12_fu_793_p3 = sub_ln342_fu_787_p2[32'd13];

assign tmp_13_fu_805_p3 = sub_ln342_fu_787_p2[32'd12];

assign tmp_14_fu_861_p3 = sub_ln343_fu_855_p2[32'd13];

assign tmp_15_fu_873_p3 = sub_ln343_fu_855_p2[32'd12];

assign tmp_16_fu_429_p3 = sub_ln353_fu_423_p2[32'd13];

assign tmp_17_fu_441_p3 = sub_ln353_fu_423_p2[32'd12];

assign tmp_18_fu_496_p3 = sub_ln354_fu_490_p2[32'd13];

assign tmp_18_i_fu_1269_p5 = {{{{{{1'd0}, {zext_ln411_fu_1266_p1}}}, {event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s}}}, {event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_1}};

assign tmp_19_fu_508_p3 = sub_ln354_fu_490_p2[32'd12];

assign tmp_20_i_fu_393_p5 = {{{{{{1'd0}, {trunc_ln387_fu_390_p1}}}, {event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_4}}}, {event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_5}};

assign tmp_21_i_fu_354_p4 = {{sample_n_load_reg_1320[6:5]}};

assign tmp_22_i_fu_367_p5 = {{{{{{1'd0}, {zext_ln399_fu_363_p1}}}, {event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_2}}}, {event_writer_stream_stream_stream_ap_uint_ap_uint_ap_uint_ap_int_128_s_3}};

assign tmp_8_fu_961_p3 = sub_ln331_fu_955_p2[32'd13];

assign tmp_9_fu_973_p3 = sub_ln331_fu_955_p2[32'd12];

assign tmp_fu_309_p3 = {{apv_id_1}, {sample_n}};

assign tmp_i_nbreadreq_fu_178_p3 = s_avgBHeader_empty_n;

assign trunc_ln293_fu_1173_p1 = s_avgBHeader_dout[1:0];

assign trunc_ln331_fu_969_p1 = sub_ln331_fu_955_p2[12:0];

assign trunc_ln332_fu_1037_p1 = sub_ln332_fu_1023_p2[12:0];

assign trunc_ln342_fu_801_p1 = sub_ln342_fu_787_p2[12:0];

assign trunc_ln343_fu_869_p1 = sub_ln343_fu_855_p2[12:0];

assign trunc_ln353_fu_437_p1 = sub_ln353_fu_423_p2[12:0];

assign trunc_ln354_fu_504_p1 = sub_ln354_fu_490_p2[12:0];

assign trunc_ln387_fu_390_p1 = sample_n_load_reg_1320[4:0];

assign xor_ln331_1_fu_993_p2 = (tmp_9_fu_973_p3 ^ tmp_8_fu_961_p3);

assign xor_ln331_fu_981_p2 = (tmp_8_fu_961_p3 ^ 1'd1);

assign xor_ln332_1_fu_1061_p2 = (tmp_11_fu_1041_p3 ^ tmp_10_fu_1029_p3);

assign xor_ln332_fu_1049_p2 = (tmp_10_fu_1029_p3 ^ 1'd1);

assign xor_ln342_1_fu_825_p2 = (tmp_13_fu_805_p3 ^ tmp_12_fu_793_p3);

assign xor_ln342_fu_813_p2 = (tmp_12_fu_793_p3 ^ 1'd1);

assign xor_ln343_1_fu_893_p2 = (tmp_15_fu_873_p3 ^ tmp_14_fu_861_p3);

assign xor_ln343_fu_881_p2 = (tmp_14_fu_861_p3 ^ 1'd1);

assign xor_ln353_1_fu_461_p2 = (tmp_17_fu_441_p3 ^ tmp_16_fu_429_p3);

assign xor_ln353_fu_449_p2 = (tmp_16_fu_429_p3 ^ 1'd1);

assign xor_ln354_1_fu_528_p2 = (tmp_19_fu_508_p3 ^ tmp_18_fu_496_p3);

assign xor_ln354_fu_516_p2 = (tmp_18_fu_496_p3 ^ 1'd1);

assign zext_ln305_cast_fu_1292_p5 = {{{{{{11'd1344}, {fiber_read_reg_1361}}}, {11'd0}}}, {mpd_id_1_reg_1410}};

assign zext_ln305_fu_1302_p1 = zext_ln305_cast_fu_1292_p5;

assign zext_ln316_fu_1150_p1 = cnt;

assign zext_ln366_fu_317_p1 = tmp_fu_309_p3;

assign zext_ln371_fu_724_p1 = sum_thr_fu_714_p2;

assign zext_ln377_fu_764_p1 = grp_fu_288_p2;

assign zext_ln390_fu_405_p1 = tmp_20_i_fu_393_p5;

assign zext_ln399_fu_363_p1 = tmp_21_i_fu_354_p4;

assign zext_ln402_fu_379_p1 = tmp_22_i_fu_367_p5;

assign zext_ln411_fu_1266_p1 = apv_id_1_load_reg_1315_pp0_iter0_reg;

assign zext_ln414_fu_1281_p1 = tmp_18_i_fu_1269_p5;

assign zext_ln417_fu_1117_p1 = grp_fu_288_p2;

endmodule //mpd_data_processor_main_event_writer
