// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mpd_data_processor_main_frame_decoder (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_evIn_dout,
        s_evIn_empty_n,
        s_evIn_read,
        s_avgASamples_din,
        s_avgASamples_num_data_valid,
        s_avgASamples_fifo_cap,
        s_avgASamples_full_n,
        s_avgASamples_write,
        s_avgAPreHeader_din,
        s_avgAPreHeader_num_data_valid,
        s_avgAPreHeader_fifo_cap,
        s_avgAPreHeader_full_n,
        s_avgAPreHeader_write,
        start_out,
        start_write,
        m_offset_address0,
        m_offset_ce0,
        m_offset_q0
);

parameter    ap_ST_iter0_fsm_state1 = 2'd1;
parameter    ap_ST_iter0_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state3 = 3'd2;
parameter    ap_ST_iter1_fsm_state4 = 3'd4;
parameter    ap_ST_iter1_fsm_state0 = 3'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [32:0] s_evIn_dout;
input   s_evIn_empty_n;
output   s_evIn_read;
output  [12:0] s_avgASamples_din;
input  [2:0] s_avgASamples_num_data_valid;
input  [2:0] s_avgASamples_fifo_cap;
input   s_avgASamples_full_n;
output   s_avgASamples_write;
output  [63:0] s_avgAPreHeader_din;
input  [1:0] s_avgAPreHeader_num_data_valid;
input  [1:0] s_avgAPreHeader_fifo_cap;
input   s_avgAPreHeader_full_n;
output   s_avgAPreHeader_write;
output   start_out;
output   start_write;
output  [9:0] m_offset_address0;
output   m_offset_ce0;
input  [25:0] m_offset_q0;

reg ap_done;
reg ap_idle;
reg s_evIn_read;
reg[12:0] s_avgASamples_din;
reg s_avgASamples_write;
reg[63:0] s_avgAPreHeader_din;
reg s_avgAPreHeader_write;
reg start_write;
reg[9:0] m_offset_address0;
reg m_offset_ce0;

reg    real_start;
reg    start_once_reg;
reg   [1:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [2:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg    internal_ap_ready;
wire    ap_CS_iter0_fsm_state2;
reg   [1:0] ps_load_reg_938;
reg   [0:0] tmp_2_i_reg_942;
reg    ap_predicate_op22_read_state2;
reg   [0:0] tmp_1_i_reg_960;
reg    ap_predicate_op53_read_state2;
reg   [0:0] tmp_i_reg_964;
reg    ap_predicate_op75_read_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg   [1:0] ps_load_reg_938_pp0_iter0_reg;
reg   [0:0] tmp_2_i_reg_942_pp0_iter0_reg;
reg    ap_predicate_op96_write_state3;
reg   [0:0] tmp_1_i_reg_960_pp0_iter0_reg;
reg   [0:0] val_end_reg_984;
reg   [0:0] icmp_ln59_reg_988;
reg    ap_predicate_op126_write_state3;
reg    ap_predicate_op136_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state3;
reg    ap_predicate_op147_write_state4;
reg    ap_block_state4_pp0_stage1_iter1;
wire    ap_CS_iter1_fsm_state4;
reg    ap_done_reg;
reg   [1:0] ps;
reg   [19:0] avg_pre_header_sum;
reg   [7:0] avg_pre_header_cnt;
reg   [4:0] mpd_id;
reg   [0:0] avg_pre_header_tag;
reg   [3:0] apv_id;
reg   [5:0] adc_word_cnt;
reg   [12:0] minmax_min;
reg   [12:0] minmax_max;
reg    s_evIn_blk_n;
reg    s_avgAPreHeader_blk_n;
reg    s_avgASamples_blk_n;
wire   [1:0] ps_load_load_fu_343_p1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] grp_nbreadreq_fu_144_p3;
reg   [5:0] adc_word_cnt_load_reg_946;
wire   [0:0] icmp_ln111_fu_368_p2;
reg   [0:0] icmp_ln111_reg_956;
wire  signed [12:0] adc_fu_442_p3;
reg  signed [12:0] adc_reg_968;
wire  signed [12:0] adc_1_fu_530_p3;
reg  signed [12:0] adc_1_reg_976;
wire   [0:0] val_end_fu_555_p3;
wire   [0:0] icmp_ln59_fu_563_p2;
wire   [3:0] tmp_10_i_fu_569_p4;
reg   [3:0] tmp_10_i_reg_992;
wire   [0:0] or_ln105_fu_784_p2;
wire   [19:0] select_ln105_fu_790_p3;
wire   [7:0] select_ln105_1_fu_798_p3;
wire   [19:0] zext_ln81_fu_901_p1;
wire   [0:0] ap_phi_reg_pp0_iter0_avg_pre_header_sum_flag_2_i_reg_193;
reg   [0:0] ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_2_i_reg_193;
wire   [1:0] ap_phi_reg_pp0_iter0_avg_pre_header_sum_new_2_i_reg_213;
reg   [1:0] ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_2_i_reg_213;
wire   [0:0] ap_phi_reg_pp0_iter0_avg_pre_header_cnt_flag_2_i_reg_233;
reg   [0:0] ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_2_i_reg_233;
wire   [0:0] ap_phi_mux_avg_pre_header_sum_flag_6_i_phi_fu_257_p10;
wire   [0:0] ap_phi_reg_pp0_iter0_avg_pre_header_sum_flag_6_i_reg_253;
reg   [0:0] ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_6_i_reg_253;
wire   [19:0] ap_phi_reg_pp0_iter0_avg_pre_header_sum_new_6_i_reg_273;
reg   [19:0] ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_6_i_reg_273;
wire   [0:0] ap_phi_mux_avg_pre_header_cnt_flag_6_i_phi_fu_296_p10;
wire   [0:0] ap_phi_reg_pp0_iter0_avg_pre_header_cnt_flag_6_i_reg_292;
reg   [0:0] ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_6_i_reg_292;
wire   [7:0] ap_phi_reg_pp0_iter0_avg_pre_header_cnt_new_6_i_reg_312;
reg   [7:0] ap_phi_reg_pp0_iter1_avg_pre_header_cnt_new_6_i_reg_312;
wire   [63:0] zext_ln87_fu_363_p1;
wire   [63:0] zext_ln75_fu_609_p1;
wire   [0:0] icmp_ln39_fu_638_p2;
wire   [5:0] add_ln114_fu_544_p2;
wire   [12:0] trunc_ln76_fu_848_p1;
wire   [63:0] zext_ln67_fu_843_p1;
wire   [63:0] zext_ln56_fu_896_p1;
wire   [63:0] zext_ln119_fu_921_p1;
wire   [9:0] tmp_fu_355_p3;
wire   [12:0] trunc_ln92_fu_374_p1;
wire   [12:0] trunc_ln92_1_fu_378_p1;
wire  signed [13:0] sext_ln92_fu_382_p1;
wire  signed [13:0] sext_ln92_1_fu_386_p1;
wire   [13:0] sub_ln92_fu_390_p2;
wire   [0:0] tmp_3_fu_396_p3;
wire   [0:0] tmp_4_fu_408_p3;
wire   [0:0] xor_ln92_fu_416_p2;
wire   [0:0] and_ln92_fu_422_p2;
wire   [0:0] xor_ln92_1_fu_428_p2;
wire   [12:0] select_ln92_fu_434_p3;
wire   [12:0] trunc_ln92_2_fu_404_p1;
wire   [12:0] tmp_i_33_fu_450_p4;
wire   [12:0] tmp_7_i_fu_460_p4;
wire  signed [13:0] sext_ln102_fu_470_p1;
wire  signed [13:0] sext_ln102_1_fu_474_p1;
wire   [13:0] sub_ln102_fu_478_p2;
wire   [0:0] tmp_5_fu_484_p3;
wire   [0:0] tmp_6_fu_496_p3;
wire   [0:0] xor_ln102_fu_504_p2;
wire   [0:0] and_ln102_fu_510_p2;
wire   [0:0] xor_ln102_1_fu_516_p2;
wire   [12:0] select_ln102_fu_522_p3;
wire   [12:0] trunc_ln102_fu_492_p1;
wire   [4:0] grp_fu_333_p4;
wire   [6:0] tmp_1_fu_597_p3;
wire  signed [9:0] sext_ln75_fu_605_p1;
wire   [0:0] icmp_ln95_fu_678_p2;
wire   [0:0] icmp_ln95_1_fu_693_p2;
wire   [0:0] xor_ln95_fu_683_p2;
wire   [0:0] xor_ln95_1_fu_698_p2;
wire  signed [19:0] sext_ln97_fu_710_p1;
wire   [0:0] and_ln95_fu_704_p2;
wire   [19:0] add_ln97_fu_713_p2;
wire   [7:0] add_ln98_fu_719_p2;
wire   [0:0] icmp_ln105_fu_741_p2;
wire   [0:0] icmp_ln105_1_fu_752_p2;
wire   [0:0] xor_ln105_fu_746_p2;
wire   [0:0] xor_ln105_1_fu_757_p2;
wire   [19:0] select_ln95_fu_725_p3;
wire  signed [19:0] sext_ln107_fu_769_p1;
wire   [7:0] select_ln95_1_fu_733_p3;
wire   [0:0] and_ln105_fu_763_p2;
wire   [19:0] add_ln107_fu_772_p2;
wire   [7:0] add_ln108_fu_778_p2;
wire   [10:0] tmp_11_i_fu_810_p4;
wire   [19:0] tmp_12_i_fu_819_p5;
wire   [40:0] zext_ln67_cast_fu_831_p5;
wire   [39:0] shl_ln_fu_874_p3;
wire   [39:0] or_ln56_fu_882_p2;
wire   [40:0] zext_ln56_cast_fu_888_p3;
wire   [40:0] tmp_4_i_fu_909_p5;
reg   [1:0] ap_NS_iter0_fsm;
reg   [2:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter0_fsm_state2_blk;
reg    ap_ST_iter1_fsm_state3_blk;
reg    ap_ST_iter1_fsm_state4_blk;
reg    ap_condition_256;
reg    ap_condition_150;
reg    ap_condition_246;
reg    ap_condition_268;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_iter0_fsm = 2'd1;
#0 ap_CS_iter1_fsm = 3'd1;
#0 ap_done_reg = 1'b0;
#0 ps = 2'd0;
#0 avg_pre_header_sum = 20'd0;
#0 avg_pre_header_cnt = 8'd0;
#0 mpd_id = 5'd0;
#0 avg_pre_header_tag = 1'd0;
#0 apv_id = 4'd0;
#0 adc_word_cnt = 6'd0;
#0 minmax_min = 13'd0;
#0 minmax_max = 13'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_150)) begin
        if ((1'b1 == ap_condition_256)) begin
            adc_word_cnt <= 6'd0;
        end else if (((tmp_2_i_reg_942 == 1'd1) & (ps_load_reg_938 == 2'd2))) begin
            adc_word_cnt <= add_ln114_fu_544_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd1) & (val_end_fu_555_p3 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_2_i_reg_233 <= 1'd1;
    end else if (((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd0) & (val_end_fu_555_p3 == 1'd0)) | (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 
    == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (val_end_fu_555_p3 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_2_i_reg_233 <= 1'd0;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_2_i_reg_233 <= ap_phi_reg_pp0_iter0_avg_pre_header_cnt_flag_2_i_reg_233;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (tmp_2_i_reg_942_pp0_iter0_reg == 1'd1) & (ps_load_reg_938_pp0_iter0_reg == 2'd2) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_6_i_reg_292 <= or_ln105_fu_784_p2;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ps_load_reg_938_pp0_iter0_reg == 2'd1) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_6_i_reg_292 <= ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_2_i_reg_233;
    end else if (((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ps_load_reg_938_pp0_iter0_reg == 2'd0) & (1'b1 == ap_CS_iter1_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 
    == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (ps_load_reg_938 == 2'd3) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_6_i_reg_292 <= 1'd0;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_6_i_reg_292 <= ap_phi_reg_pp0_iter0_avg_pre_header_cnt_flag_6_i_reg_292;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (tmp_2_i_reg_942_pp0_iter0_reg == 1'd1) & (ps_load_reg_938_pp0_iter0_reg == 2'd2) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_new_6_i_reg_312 <= select_ln105_1_fu_798_p3;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ps_load_reg_938_pp0_iter0_reg == 2'd1) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_new_6_i_reg_312 <= 8'd0;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_cnt_new_6_i_reg_312 <= ap_phi_reg_pp0_iter0_avg_pre_header_cnt_new_6_i_reg_312;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd0) & (val_end_fu_555_p3 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_2_i_reg_193 <= 1'd0;
    end else if (((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (val_end_fu_555_p3 == 1'd1)) | (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n 
    == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd1) & (val_end_fu_555_p3 == 1'd0)))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_2_i_reg_193 <= 1'd1;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_2_i_reg_193 <= ap_phi_reg_pp0_iter0_avg_pre_header_sum_flag_2_i_reg_193;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (tmp_2_i_reg_942_pp0_iter0_reg == 1'd1) & (ps_load_reg_938_pp0_iter0_reg == 2'd2) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_6_i_reg_253 <= or_ln105_fu_784_p2;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ps_load_reg_938_pp0_iter0_reg == 2'd1) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_6_i_reg_253 <= ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_2_i_reg_193;
    end else if (((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ps_load_reg_938_pp0_iter0_reg == 2'd0) & (1'b1 == ap_CS_iter1_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 
    == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (ps_load_reg_938 == 2'd3) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_6_i_reg_253 <= 1'd0;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_6_i_reg_253 <= ap_phi_reg_pp0_iter0_avg_pre_header_sum_flag_6_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd0) & (val_end_fu_555_p3 == 1'd0)) | (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 
    == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd1) & (val_end_fu_555_p3 == 1'd0)))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_2_i_reg_213 <= 2'd0;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (val_end_fu_555_p3 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_2_i_reg_213 <= 2'd2;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_2_i_reg_213 <= ap_phi_reg_pp0_iter0_avg_pre_header_sum_new_2_i_reg_213;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (tmp_2_i_reg_942_pp0_iter0_reg == 1'd1) & (ps_load_reg_938_pp0_iter0_reg == 2'd2) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_6_i_reg_273 <= select_ln105_fu_790_p3;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ps_load_reg_938_pp0_iter0_reg == 2'd1) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_6_i_reg_273 <= zext_ln81_fu_901_p1;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_6_i_reg_273 <= ap_phi_reg_pp0_iter0_avg_pre_header_sum_new_6_i_reg_273;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_246)) begin
        if ((val_end_fu_555_p3 == 1'd1)) begin
            avg_pre_header_tag <= 1'd1;
        end else if (((icmp_ln59_fu_563_p2 == 1'd1) & (val_end_fu_555_p3 == 1'd0))) begin
            avg_pre_header_tag <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_i_reg_964 == 1'd1) & (ps_load_reg_938 == 2'd0) & (icmp_ln39_fu_638_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n 
    == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (ps_load_reg_938 == 2'd3) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        ps <= 2'd1;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (val_end_fu_555_p3 == 1'd1))) begin
        ps <= 2'd0;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd1) & (val_end_fu_555_p3 == 1'd0))) begin
        ps <= 2'd2;
    end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_2_i_reg_942 == 1'd1) & (ps_load_reg_938 == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln111_reg_956 == 1'd1))) begin
        ps <= 2'd3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_2_i_reg_942 == 1'd1) & (ps_load_reg_938 == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        adc_1_reg_976 <= adc_1_fu_530_p3;
        adc_reg_968 <= adc_fu_442_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_144_p3 == 1'd1) & (ps_load_load_fu_343_p1 == 2'd2))) begin
        adc_word_cnt_load_reg_946 <= adc_word_cnt;
        icmp_ln111_reg_956 <= icmp_ln111_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd1) & (val_end_fu_555_p3 == 1'd0))) begin
        apv_id <= {{s_evIn_dout[26:23]}};
        tmp_10_i_reg_992 <= {{s_evIn_dout[26:23]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1))) & (ap_phi_mux_avg_pre_header_cnt_flag_6_i_phi_fu_296_p10 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state4))) begin
        avg_pre_header_cnt <= ap_phi_reg_pp0_iter1_avg_pre_header_cnt_new_6_i_reg_312;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_phi_mux_avg_pre_header_sum_flag_6_i_phi_fu_257_p10 == 1'd1))) begin
        avg_pre_header_sum <= ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_6_i_reg_273;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (val_end_fu_555_p3 == 1'd0))) begin
        icmp_ln59_reg_988 <= icmp_ln59_fu_563_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ps_load_reg_938_pp0_iter0_reg == 2'd1) & (1'b1 == ap_CS_iter1_fsm_state3) & (icmp_ln59_reg_988 == 1'd1) & (val_end_reg_984 == 1'd0) & (tmp_1_i_reg_960_pp0_iter0_reg == 1'd1))) begin
        minmax_max <= {{m_offset_q0[25:13]}};
        minmax_min <= trunc_ln76_fu_848_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_i_reg_964 == 1'd1) & (ps_load_reg_938 == 2'd0) & (icmp_ln39_fu_638_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        mpd_id <= {{s_evIn_dout[20:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ps_load_reg_938 <= ps;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ps_load_reg_938_pp0_iter0_reg <= ps_load_reg_938;
        tmp_1_i_reg_960_pp0_iter0_reg <= tmp_1_i_reg_960;
        tmp_2_i_reg_942_pp0_iter0_reg <= tmp_2_i_reg_942;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ps_load_load_fu_343_p1 == 2'd1))) begin
        tmp_1_i_reg_960 <= grp_nbreadreq_fu_144_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ps_load_load_fu_343_p1 == 2'd2))) begin
        tmp_2_i_reg_942 <= grp_nbreadreq_fu_144_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ps_load_load_fu_343_p1 == 2'd0))) begin
        tmp_i_reg_964 <= grp_nbreadreq_fu_144_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        val_end_reg_984 <= s_evIn_dout[32'd32];
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)))) begin
        ap_ST_iter0_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1)))) begin
        ap_ST_iter1_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1))) begin
        ap_ST_iter1_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd1) & (val_end_fu_555_p3 == 1'd0))) begin
        m_offset_address0 = zext_ln75_fu_609_p1;
    end else if (((1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_144_p3 == 1'd1) & (ps_load_load_fu_343_p1 == 2'd2) & (real_start == 1'b1))) begin
        m_offset_address0 = zext_ln87_fu_363_p1;
    end else begin
        m_offset_address0 = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_nbreadreq_fu_144_p3 == 1'd1) & (ps_load_load_fu_343_p1 == 2'd2)) | (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 
    == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2) & (icmp_ln59_fu_563_p2 == 1'd1) & (val_end_fu_555_p3 == 1'd0)))) begin
        m_offset_ce0 = 1'b1;
    end else begin
        m_offset_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op136_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op126_write_state3 == 1'b1)) | ((ps_load_reg_938_pp0_iter0_reg == 2'd3) & (1'b1 == ap_CS_iter1_fsm_state3)))) begin
        s_avgAPreHeader_blk_n = s_avgAPreHeader_full_n;
    end else begin
        s_avgAPreHeader_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_268)) begin
        if ((ps_load_reg_938_pp0_iter0_reg == 2'd3)) begin
            s_avgAPreHeader_din = zext_ln119_fu_921_p1;
        end else if ((ap_predicate_op136_write_state3 == 1'b1)) begin
            s_avgAPreHeader_din = zext_ln56_fu_896_p1;
        end else if ((ap_predicate_op126_write_state3 == 1'b1)) begin
            s_avgAPreHeader_din = zext_ln67_fu_843_p1;
        end else begin
            s_avgAPreHeader_din = 'bx;
        end
    end else begin
        s_avgAPreHeader_din = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op136_write_state3 == 1'b1)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op126_write_state3 == 1'b1)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg 
    == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ps_load_reg_938_pp0_iter0_reg == 2'd3) & (1'b1 == ap_CS_iter1_fsm_state3)))) begin
        s_avgAPreHeader_write = 1'b1;
    end else begin
        s_avgAPreHeader_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op96_write_state3 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state3)) | ((1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)))) begin
        s_avgASamples_blk_n = s_avgASamples_full_n;
    end else begin
        s_avgASamples_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1))) begin
        s_avgASamples_din = adc_1_reg_976;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ap_predicate_op96_write_state3 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        s_avgASamples_din = adc_reg_968;
    end else begin
        s_avgASamples_din = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (ap_predicate_op96_write_state3 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state3)))) begin
        s_avgASamples_write = 1'b1;
    end else begin
        s_avgASamples_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op75_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | ((ap_predicate_op53_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | ((ap_predicate_op22_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        s_evIn_blk_n = s_evIn_empty_n;
    end else begin
        s_evIn_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (ap_predicate_op75_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 
    == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (ap_predicate_op53_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n 
    == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (ap_predicate_op22_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        s_evIn_read = 1'b1;
    end else begin
        s_evIn_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end
        end
        ap_ST_iter0_fsm_state2 : begin
            if (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1)))))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state4;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end
        end
        ap_ST_iter1_fsm_state4 : begin
            if ((~(((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0))) & ~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1))) & ((1'b0 == ap_CS_iter0_fsm_state2) | ((1'b1 == ap_CS_iter0_fsm_state2) & (((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state4;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign adc_1_fu_530_p3 = ((xor_ln102_1_fu_516_p2[0:0] == 1'b1) ? select_ln102_fu_522_p3 : trunc_ln102_fu_492_p1);

assign adc_fu_442_p3 = ((xor_ln92_1_fu_428_p2[0:0] == 1'b1) ? select_ln92_fu_434_p3 : trunc_ln92_2_fu_404_p1);

assign add_ln107_fu_772_p2 = ($signed(select_ln95_fu_725_p3) + $signed(sext_ln107_fu_769_p1));

assign add_ln108_fu_778_p2 = (select_ln95_1_fu_733_p3 + 8'd1);

assign add_ln114_fu_544_p2 = (adc_word_cnt_load_reg_946 + 6'd1);

assign add_ln97_fu_713_p2 = ($signed(avg_pre_header_sum) + $signed(sext_ln97_fu_710_p1));

assign add_ln98_fu_719_p2 = (avg_pre_header_cnt + 8'd1);

assign and_ln102_fu_510_p2 = (xor_ln102_fu_504_p2 & tmp_6_fu_496_p3);

assign and_ln105_fu_763_p2 = (xor_ln105_fu_746_p2 & xor_ln105_1_fu_757_p2);

assign and_ln92_fu_422_p2 = (xor_ln92_fu_416_p2 & tmp_4_fu_408_p3);

assign and_ln95_fu_704_p2 = (xor_ln95_fu_683_p2 & xor_ln95_1_fu_698_p2);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter0_fsm_state2 = ap_CS_iter0_fsm[32'd1];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state3 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter1_fsm_state4 = ap_CS_iter1_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state4_pp0_stage1_iter1 = ((s_avgASamples_full_n == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1));
end

always @ (*) begin
    ap_condition_150 = (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state2));
end

always @ (*) begin
    ap_condition_246 = (~((ap_done_reg == 1'b1) | ((s_avgASamples_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op147_write_state4 == 1'b1)) | ((ap_predicate_op75_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op53_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((ap_predicate_op22_read_state2 == 1'b1) & (s_evIn_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))))) & (tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state2));
end

always @ (*) begin
    ap_condition_256 = ((tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1) & (icmp_ln59_fu_563_p2 == 1'd1) & (val_end_fu_555_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_268 = (~((ap_done_reg == 1'b1) | ((ap_predicate_op96_write_state3 == 1'b1) & (s_avgASamples_full_n == 1'b0)) | ((s_avgAPreHeader_full_n == 1'b0) & (ps_load_reg_938_pp0_iter0_reg == 2'd3)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op136_write_state3 == 1'b1)) | ((s_avgAPreHeader_full_n == 1'b0) & (ap_predicate_op126_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state3));
end

assign ap_phi_mux_avg_pre_header_cnt_flag_6_i_phi_fu_296_p10 = ap_phi_reg_pp0_iter1_avg_pre_header_cnt_flag_6_i_reg_292;

assign ap_phi_mux_avg_pre_header_sum_flag_6_i_phi_fu_257_p10 = ap_phi_reg_pp0_iter1_avg_pre_header_sum_flag_6_i_reg_253;

assign ap_phi_reg_pp0_iter0_avg_pre_header_cnt_flag_2_i_reg_233 = 1'd0;

assign ap_phi_reg_pp0_iter0_avg_pre_header_cnt_flag_6_i_reg_292 = 1'd0;

assign ap_phi_reg_pp0_iter0_avg_pre_header_cnt_new_6_i_reg_312 = 'bx;

assign ap_phi_reg_pp0_iter0_avg_pre_header_sum_flag_2_i_reg_193 = 1'd0;

assign ap_phi_reg_pp0_iter0_avg_pre_header_sum_flag_6_i_reg_253 = 1'd0;

assign ap_phi_reg_pp0_iter0_avg_pre_header_sum_new_2_i_reg_213 = 'bx;

assign ap_phi_reg_pp0_iter0_avg_pre_header_sum_new_6_i_reg_273 = 'bx;

always @ (*) begin
    ap_predicate_op126_write_state3 = ((ps_load_reg_938_pp0_iter0_reg == 2'd1) & (icmp_ln59_reg_988 == 1'd1) & (val_end_reg_984 == 1'd0) & (tmp_1_i_reg_960_pp0_iter0_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op136_write_state3 = ((ps_load_reg_938_pp0_iter0_reg == 2'd1) & (val_end_reg_984 == 1'd1) & (tmp_1_i_reg_960_pp0_iter0_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op147_write_state4 = ((tmp_2_i_reg_942_pp0_iter0_reg == 1'd1) & (ps_load_reg_938_pp0_iter0_reg == 2'd2));
end

always @ (*) begin
    ap_predicate_op22_read_state2 = ((tmp_2_i_reg_942 == 1'd1) & (ps_load_reg_938 == 2'd2));
end

always @ (*) begin
    ap_predicate_op53_read_state2 = ((tmp_1_i_reg_960 == 1'd1) & (ps_load_reg_938 == 2'd1));
end

always @ (*) begin
    ap_predicate_op75_read_state2 = ((tmp_i_reg_964 == 1'd1) & (ps_load_reg_938 == 2'd0));
end

always @ (*) begin
    ap_predicate_op96_write_state3 = ((tmp_2_i_reg_942_pp0_iter0_reg == 1'd1) & (ps_load_reg_938_pp0_iter0_reg == 2'd2));
end

assign ap_ready = internal_ap_ready;

assign grp_fu_333_p4 = {{s_evIn_dout[31:27]}};

assign grp_nbreadreq_fu_144_p3 = s_evIn_empty_n;

assign icmp_ln105_1_fu_752_p2 = (($signed(minmax_max) < $signed(adc_1_reg_976)) ? 1'b1 : 1'b0);

assign icmp_ln105_fu_741_p2 = (($signed(adc_1_reg_976) < $signed(minmax_min)) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_368_p2 = ((adc_word_cnt == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_638_p2 = ((grp_fu_333_p4 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_563_p2 = ((grp_fu_333_p4 == 5'd20) ? 1'b1 : 1'b0);

assign icmp_ln95_1_fu_693_p2 = (($signed(minmax_max) < $signed(adc_reg_968)) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_678_p2 = (($signed(adc_reg_968) < $signed(minmax_min)) ? 1'b1 : 1'b0);

assign or_ln105_fu_784_p2 = (and_ln95_fu_704_p2 | and_ln105_fu_763_p2);

assign or_ln56_fu_882_p2 = (shl_ln_fu_874_p3 | 40'd2);

assign ps_load_load_fu_343_p1 = ps;

assign select_ln102_fu_522_p3 = ((and_ln102_fu_510_p2[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln105_1_fu_798_p3 = ((and_ln105_fu_763_p2[0:0] == 1'b1) ? add_ln108_fu_778_p2 : select_ln95_1_fu_733_p3);

assign select_ln105_fu_790_p3 = ((and_ln105_fu_763_p2[0:0] == 1'b1) ? add_ln107_fu_772_p2 : select_ln95_fu_725_p3);

assign select_ln92_fu_434_p3 = ((and_ln92_fu_422_p2[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln95_1_fu_733_p3 = ((and_ln95_fu_704_p2[0:0] == 1'b1) ? add_ln98_fu_719_p2 : avg_pre_header_cnt);

assign select_ln95_fu_725_p3 = ((and_ln95_fu_704_p2[0:0] == 1'b1) ? add_ln97_fu_713_p2 : avg_pre_header_sum);

assign sext_ln102_1_fu_474_p1 = $signed(tmp_7_i_fu_460_p4);

assign sext_ln102_fu_470_p1 = $signed(tmp_i_33_fu_450_p4);

assign sext_ln107_fu_769_p1 = adc_1_reg_976;

assign sext_ln75_fu_605_p1 = $signed(tmp_1_fu_597_p3);

assign sext_ln92_1_fu_386_p1 = $signed(trunc_ln92_1_fu_378_p1);

assign sext_ln92_fu_382_p1 = $signed(trunc_ln92_fu_374_p1);

assign sext_ln97_fu_710_p1 = adc_reg_968;

assign shl_ln_fu_874_p3 = {{avg_pre_header_cnt}, {32'd0}};

assign start_out = real_start;

assign sub_ln102_fu_478_p2 = ($signed(sext_ln102_fu_470_p1) - $signed(sext_ln102_1_fu_474_p1));

assign sub_ln92_fu_390_p2 = ($signed(sext_ln92_fu_382_p1) - $signed(sext_ln92_1_fu_386_p1));

assign tmp_10_i_fu_569_p4 = {{s_evIn_dout[26:23]}};

assign tmp_11_i_fu_810_p4 = {{{mpd_id}, {tmp_10_i_reg_992}}, {2'd1}};

assign tmp_12_i_fu_819_p5 = {{avg_pre_header_sum[19:11]}, {tmp_11_i_fu_810_p4}};

assign tmp_1_fu_597_p3 = {{3'd4}, {tmp_10_i_fu_569_p4}};

assign tmp_3_fu_396_p3 = sub_ln92_fu_390_p2[32'd13];

assign tmp_4_fu_408_p3 = sub_ln92_fu_390_p2[32'd12];

assign tmp_4_i_fu_909_p5 = {{{{avg_pre_header_tag}, {avg_pre_header_cnt}}, {12'd0}}, {avg_pre_header_sum}};

assign tmp_5_fu_484_p3 = sub_ln102_fu_478_p2[32'd13];

assign tmp_6_fu_496_p3 = sub_ln102_fu_478_p2[32'd12];

assign tmp_7_i_fu_460_p4 = {{m_offset_q0[25:13]}};

assign tmp_fu_355_p3 = {{apv_id}, {adc_word_cnt}};

assign tmp_i_33_fu_450_p4 = {{s_evIn_dout[25:13]}};

assign trunc_ln102_fu_492_p1 = sub_ln102_fu_478_p2[12:0];

assign trunc_ln76_fu_848_p1 = m_offset_q0[12:0];

assign trunc_ln92_1_fu_378_p1 = m_offset_q0[12:0];

assign trunc_ln92_2_fu_404_p1 = sub_ln92_fu_390_p2[12:0];

assign trunc_ln92_fu_374_p1 = s_evIn_dout[12:0];

assign val_end_fu_555_p3 = s_evIn_dout[32'd32];

assign xor_ln102_1_fu_516_p2 = (tmp_6_fu_496_p3 ^ tmp_5_fu_484_p3);

assign xor_ln102_fu_504_p2 = (tmp_5_fu_484_p3 ^ 1'd1);

assign xor_ln105_1_fu_757_p2 = (icmp_ln105_1_fu_752_p2 ^ 1'd1);

assign xor_ln105_fu_746_p2 = (icmp_ln105_fu_741_p2 ^ 1'd1);

assign xor_ln92_1_fu_428_p2 = (tmp_4_fu_408_p3 ^ tmp_3_fu_396_p3);

assign xor_ln92_fu_416_p2 = (tmp_3_fu_396_p3 ^ 1'd1);

assign xor_ln95_1_fu_698_p2 = (icmp_ln95_1_fu_693_p2 ^ 1'd1);

assign xor_ln95_fu_683_p2 = (icmp_ln95_fu_678_p2 ^ 1'd1);

assign zext_ln119_fu_921_p1 = tmp_4_i_fu_909_p5;

assign zext_ln56_cast_fu_888_p3 = {{1'd1}, {or_ln56_fu_882_p2}};

assign zext_ln56_fu_896_p1 = zext_ln56_cast_fu_888_p3;

assign zext_ln67_cast_fu_831_p5 = {{{{{{1'd1}, {avg_pre_header_cnt}}}, {12'd0}}}, {tmp_12_i_fu_819_p5}};

assign zext_ln67_fu_843_p1 = zext_ln67_cast_fu_831_p5;

assign zext_ln75_fu_609_p1 = $unsigned(sext_ln75_fu_605_p1);

assign zext_ln81_fu_901_p1 = ap_phi_reg_pp0_iter1_avg_pre_header_sum_new_2_i_reg_213;

assign zext_ln87_fu_363_p1 = tmp_fu_355_p3;

endmodule //mpd_data_processor_main_frame_decoder
